-- DS-17 selesai — siklus hidup BOM: hapus / arsip / pulihkan, diputuskan SERVER.
--
-- HANYA menyentuh baris DS-17. Nol perubahan pada task lain.
--
-- Teks panjang ditulis lewat concat_ws(chr(10), ...) sesuai aturan proyek: rangkaian
-- E'...' || E'...' pernah merusak migrasi tiga kali berturut-turut, dan galatnya menunjuk
-- ke akhir berkas, bukan ke penyebabnya.

update build_tasks
set status = 'selesai',
    completed_at = now(),
    notes = concat_ws(chr(10),
      'SELESAI 27 Agu 2026.',
      '',
      'KEPUTUSAN BISNIS (pemilik produk, 27 Agu 2026):',
      '- BOM belum dipakai           -> DIHAPUS permanen beserta baris komponennya.',
      '- BOM dipakai Work Order      -> DIARSIPKAN, tidak dihapus.',
      '- BOM dipakai batch produksi  -> DIARSIPKAN; angka batch TIDAK BOLEH berubah.',
      '- BOM diarsipkan              -> DITOLAK saat dipakai membuat Work Order baru.',
      '- Pemulihan                   -> ADA, dan hanya membuka pemakaian ke depan.',
      '- Yang memutuskan             -> SERVER, bukan pengguna.',
      '',
      'KENAPA SERVER YANG MEMUTUSKAN: pengguna tidak bisa tahu dari layar apakah sebuah',
      'BOM pernah dipakai Work Order tiga bulan lalu. Menawarkan pilihan hapus-vs-arsip',
      'berarti meminta keputusan dari orang yang tidak punya informasinya. Layar memakai',
      'SATU tombol Hapus; hasil sebenarnya dilaporkan lewat notifikasi setelah server',
      'memeriksanya. Pola yang sama dipakai Item, Supplier, dan Routing.',
      '',
      'BEDANYA DARI ROUTING, dan ini disengaja: Routing MENOLAK pengarsipan bila ada batch',
      'berjalan. BOM tidak. Batch memakai snapshotted_bom_id -- salinan bekunya sendiri --',
      'jadi mengarsipkan BOM induk tidak mengubah satu angka pun di batch itu. Yang dicegah',
      'pengarsipan adalah PEMAKAIAN BARU, dan batch yang sudah jalan bukan pemakaian baru.',
      '',
      'YANG DIBANGUN:',
      '- Kolom boms.archived_at + boms.archived_by (migrasi 20260829130000).',
      '- src/features/mrp/server/deleteOrArchiveBom.ts (deleteOrArchiveBom, restoreBom).',
      '- app/api/boms/[bomId]/route.ts (DELETE), app/api/boms/[bomId]/restore/route.ts (PATCH).',
      '- listBoms menyembunyikan yang diarsipkan secara bawaan, DI SERVER; includeArchived=true membukanya.',
      '- createWorkOrder menolak BOM yang diarsipkan.',
      '- BomsPage: saklar arsip, tombol Hapus/Pulihkan, dua Modal Carbon (yang hapus bervarian danger).',
      '',
      'BUKTI:',
      '- tests/bom_lifecycle.test.ts -- 10 uji, seluruhnya lulus.',
      '- Enam lebar wajib (360/672/768/1280/1440/1920): nol gulir menyamping, nol elemen',
      '  melewati tepi kanan, nol melewati tepi kiri.',
      '- Fixture dibuat DAN dihapus lewat layar di tenant uji; potret 91 tabel: NOL tabel berubah.',
      '',
      'DUA CACAT DITEMUKAN LEWAT MENJALANKAN, bukan lewat membaca -- keduanya lolos typecheck:',
      '1. Baris aksi memakai flex-wrap: wrap, dan di 672-1440px kedua tombol justru turun jadi',
      '   dua baris dan BERTUMPUK RAPAT -- jarak Ubah/Hapus terukur NEGATIF, kebalikan dari',
      '   aturan "aksi merusak berjauhan". Diperbaiki: nowrap + jarak tetap $spacing-07.',
      '2. listBoms mengambil archived_at di kueri lalu MENJATUHKANNYA dari objek jawaban.',
      '   Penyaringannya benar, tapi layar tidak pernah tahu sebuah baris diarsipkan, jadi',
      '   baris arsip tetap menampilkan "Ubah + Hapus" dan tombol "Pulihkan" tidak pernah',
      '   muncul. Penjaganya ditambahkan ke tests/bom_lifecycle.test.ts dan dibuktikan',
      '   berbunyi ke dua arah (merah tanpa kolomnya, hijau dengannya).',
      '',
      'KETERBATASAN YANG DILAPORKAN APA ADANYA: keadaan DIARSIPKAN tidak bisa lahir lewat',
      'layar di tenant uji, karena membuat Work Order butuh work center dan tenant uji punya',
      'nol work center -- penghalang MST-09. Cabang arsip diuji penuh di server; untuk bukti',
      'visualnya, satu kolom pada baris fixture milik sesi ini ditandai langsung, lalu',
      'dipulihkan lewat tombol Pulihkan yang sungguhan. Baris fixture itu sudah dihapus.',
      '',
      'RUJUKAN KATALOG CARBON untuk perbandingan berdampingan:',
      '- Modal (varian danger): https://carbondesignsystem.com/components/modal/usage/',
      '- Data table: https://carbondesignsystem.com/components/data-table/usage/',
      '- Notification (toast): https://carbondesignsystem.com/components/notification/usage/'
    )
where task_code = 'DS-17';
