-- Empat temuan/sapuan DICATAT, BUKAN DIKERJAKAN (25 Agu 2026) -- aturan "fokus satu task".
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  perform pastikan_kode_task_kosong('AUD-41');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AUD-41',
    'Sapu Kelas "Fungsi Kebetulan" — Data yang Dipakai untuk Hal yang Tidak Dimaksudkan',
    'AUD', 'Audit & Kepatuhan',
    'Mencari data atau baris LAIN yang punya fungsi kebetulan seperti peringatan stok terhadap status Terhambat.',
    'Menentukan apakah ada pencabutan berikutnya yang akan menghasilkan kerusakan yang DIAM.',
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'KELAS YANG DISAPU, dari kejadian nyata 25 Agu 2026: baris peringatan stok per Work',
      'Order ternyata SATU-SATUNYA hal yang membuat Work Order tampil "Terhambat".',
      'Mencabutnya akan membuat WO yang bahannya kurang tampil "Siap Mulai", tanpa satu pun',
      'hal yang gagal atau merah.',
      '',
      'YANG DICARI (kandidat, bukan daftar tertutup):',
      '  a. status yang DIHITUNG dari keberadaan baris di tabel lain;',
      '  b. penanda yang bergantung pada HITUNGAN, bukan pada nilai yang disengaja;',
      '  c. tampilan yang berubah karena ADA-TIDAKNYA sesuatu, bukan karena nilai eksplisit.',
      '',
      'CARA MENCARINYA: sisir seluruh view dan fungsi database untuk pola exists(...) /',
      'count(...) yang menentukan sebuah STATUS atau TAMPILAN, lalu untuk masing-masing',
      'tanyakan: kalau baris itu berhenti dibuat, apa yang berubah, dan apakah ada yang',
      'berbunyi?',
      '',
      'LAPORKAN DAFTARNYA, JANGAN PERBAIKI. Perbaikannya jadi task masing-masing.',
      '',
      'WAKTU YANG TEPAT: sebelum penerapan cetakan Carbon menyentuh banyak halaman, karena',
      'penerapan itu akan banyak menyentuh tampilan yang bergantung pada keberadaan data.'),
    concat_ws(chr(10),
      'Ditemukan saat mengerjakan GDG-10 (peringatan bahan gabungan), 25 Agu 2026.',
      'Aturannya sudah dicatat di HANDOFF bagian VV dan berbunyi:',
      '  "Sebelum mencabut sesuatu, cari tahu apa lagi yang bergantung padanya SECARA TIDAK',
      '   SENGAJA. Sebuah baris data bisa punya dua fungsi: yang dimaksudkan, dan yang',
      '   kebetulan. Yang kebetulan tidak tercatat di mana pun, dan hilangnya tidak',
      '   menghasilkan galat."'));

  perform pastikan_kode_task_kosong('AUD-42');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AUD-42',
    'Penjaga Kebocoran Istilah Salah Tuduh TIGA KALI — Bentuknya yang Bermasalah',
    'AUD', 'Audit & Kepatuhan',
    'Meninjau ulang cara kerja tests/ui_raw_leak_watchdog.test.ts, bukan menambal kasus ketiganya.',
    'Menentukan apakah hasil penjaga ini masih dibaca orang atau sudah mulai diabaikan.',
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DUA KALI itu pola; TIGA KALI berarti BENTUKNYA yang bermasalah, bukan kasusnya.',
      '',
      'APA YANG MEMBUATNYA BERULANG SALAH TUDUH: ia MENCOCOKKAN TEKS baris per baris tanpa',
      'memahami struktur JSX. Ia tidak tahu elemen mana yang sedang ditulis, tidak tahu apakah',
      'sebuah ekspresi benar-benar dirender ke layar atau cuma jadi nilai kontrol, dan tidak',
      'tahu apakah kata yang cocok ada di dalam komentar. Ketiga salah tuduhnya lahir dari',
      'ketiadaan ketiga pengetahuan itu:',
      '  1. kata "input" di dalam KALIMAT PENJELASAN dikira elemen <input> mentah;',
      '  2. visiting.delete(...) -- Set JavaScript biasa -- dikira penulisan ke database;',
      '  3. value={docForm.doc_type} pada <CarbonSelect> dikira enum mentah yang tampil,',
      '     padahal teks tampilnya datang dari text={t.label}.',
      '',
      'YANG PERLU DILAKUKAN:',
      '  a. SEBUTKAN BATAS ITU DI BERKASNYA secara terbuka: ini pencocokan teks, bukan parser.',
      '     Komentar yang menyebut kemampuannya tanpa menyebut batasnya memberi rasa aman yang',
      '     tidak berdasar (aturan "komentar yang menyebut risiko wajib menyebut batasnya").',
      '  b. PERTIMBANGKAN cara yang tidak bergantung pencocokan nama -- mis. mem-parse JSX',
      '     sungguhan, atau memeriksa HTML hasil render alih-alih kode sumber.',
      '  c. Bila (b) terlalu mahal, itu jawaban yang sah -- TAPI (a) tetap wajib.',
      '',
      'ALASAN INI PENTING, bukan kerapian: penjaga yang salah tuduh MELATIH ORANG MENGABAIKAN',
      'HASILNYA. Begitu itu terjadi ia tidak menjaga apa pun sambil tetap terlihat menjaga.'),
    concat_ws(chr(10),
      'Ditemukan saat mengerjakan MST-27/GDG-10, 25 Agu 2026. Salah tuduh ketiga sudah',
      'diperketat di giliran itu (mencari pembuka elemen terdekat dengan lekukan lebih',
      'dangkal, dibuktikan dua arah) -- tapi itu menambal KASUSNYA, bukan bentuknya.'));

  perform pastikan_kode_task_kosong('AUD-43');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AUD-43',
    'Sapu Test yang MENULIS Tanpa Memeriksa Galatnya',
    'AUD', 'Audit & Kepatuhan',
    'Mencari test lain yang menulis ke database tanpa memeriksa error, sehingga kegagalannya menyamar.',
    'Menentukan apakah suite bisa dipercaya saat berwarna merah.',
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'KEJADIAN NYATA yang melahirkannya: tests/ai_project_dashboard.test.ts menulis',
      'answered_by: 1, confirmed_by: 1 -- angka yang menunjuk pengguna milik PERUSAHAAN LAIN --',
      'dan tidak memeriksa galatnya. Tulisannya ditolak kunci asing, dan yang TERLIHAT adalah',
      '"progres 0%", yang terbaca seperti cacat perhitungan progres.',
      '',
      'CARA MENYAPUNYA: cari pemanggilan .insert( / .update( / .upsert( / .delete( di tests/',
      'yang hasilnya TIDAK di-destructure ke { error } atau tidak diperiksa sama sekali.',
      'Perhatikan juga rpc(...) yang errornya diabaikan.',
      '',
      'LAPORKAN DAFTARNYA. BILA BANYAK, USULKAN PENJAGA -- test yang menulis tanpa memeriksa',
      'adalah test yang belum tentu menguji apa pun, dan jumlahnya menentukan apakah ini layak',
      'dijaga otomatis atau cukup dibereskan sekali.'),
    concat_ws(chr(10),
      'Ditemukan saat mengerjakan MST-27, 25 Agu 2026. Satu kejadiannya sudah diperbaiki',
      '(memakai id milik company fixture-nya DAN memeriksa galatnya); sapuannya belum.',
      '',
      'Kelasnya sudah dicatat sebelumnya di proyek ini: "tulisan yang tidak diperiksa adalah',
      'tulisan yang belum tentu terjadi".'));

  perform pastikan_kode_task_kosong('INF-27');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'INF-27',
    'Pengawas Migrasi Menghalangi Penjaga Kurung Berjalan Sebelum Migrasinya Terpasang',
    'INF', 'Infrastruktur',
    'Dua penjaga saling menghalangi: kurung migrasi baru tidak bisa diperiksa sebelum migrasinya terpasang.',
    'Menentukan apakah penjaga kurung benar-benar terpakai, atau selalu dilewati saat paling dibutuhkan.',
    'bisa_menunggu', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'KEADAANNYA: tests/migrasi_kurung_seimbang.test.ts gunanya memeriksa migrasi BARU',
      'SEBELUM dijalankan. Tapi globalSetup tests/setup/assertMigrationsUpToDate.ts menolak',
      'menjalankan test apa pun selama ada migrasi di repo yang belum terpasang di project uji.',
      '',
      'Akibatnya, persis saat penjaga kurung paling dibutuhkan -- berkas migrasi baru yang',
      'belum diterapkan -- ia TIDAK BISA DIJALANKAN lewat vitest. Terjadi nyata 25 Agu 2026',
      'dan diakali dengan menjalankan logikanya langsung lewat skrip terpisah.',
      '',
      'KEMUNGKINAN JALAN KELUAR, pilih saat dikerjakan:',
      '  a. jadikan penjaga kurung skrip mandiri (npm run check:migrasi) yang tidak lewat',
      '     vitest sama sekali;',
      '  b. beri pengawas migrasi pengecualian untuk berkas test tertentu;',
      '  c. jalankan pemeriksaan kurung di dalam pengawas migrasi itu sendiri, sebelum ia',
      '     memutuskan menolak.',
      'Jangan melonggarkan pengawas migrasinya -- ia baru saja menutup sembilan kegagalan',
      'palsu, dan melonggarkannya mengembalikan kelas itu.'),
    concat_ws(chr(10),
      'Ditemukan saat mencatat task PMB-12 dan OVR-01, 25 Agu 2026 -- migrasinya sendiri kurang',
      'satu kurung, dan penjaganya tidak bisa dijalankan untuk menemukannya.',
      '',
      'Urgensi BISA MENUNGGU karena ada jalan memutar yang bekerja, bukan karena tidak penting.'));
end $mig$;
