-- Dua dokumen arsitektur DICATAT SEBAGAI TASK, BUKAN DIKERJAKAN (25 Agu 2026).
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  perform pastikan_kode_task_kosong('AR-01');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AR-01',
    'Rekonsiliasi Arsitektur AS-IS vs TO-BE',
    'AR', 'Arsitektur',
    'Menyandingkan keadaan sistem yang sebenarnya dengan arsitektur yang dituju, lalu memutuskan jaraknya.',
    'Menentukan apakah keputusan besar berikutnya diambil di atas peta yang benar atau di atas dugaan.',
    'bisa_menunggu', 'menunggu', 'pemilik_produk', 'Claude Code',
    concat_ws(chr(10),
      'SUMBER: docs/FABRIX_Architecture_Reconciliation_ASIS_vs_TOBE_Claude_Opus5_to_Claude_Code.md',
      '(34 bagian). Catatan kepala sudah ditambahkan di berkasnya.',
      '',
      '=== TUMPANG TINDIH — INI YANG MENGECILKAN LINGKUPNYA DARI 34 BAGIAN ===',
      'SUDAH TERCAKUP PENUH, jangan dikerjakan ulang:',
      '  S.4 Repository audit + S.6 Route audit + S.17 Navigation status',
      '      -> docs/ar0-inventaris-as-is.md (31 halaman TERVERIFIKASI PERAMBAN, bukan dibaca)',
      '         dan docs/nav-matriks-status-dan-konflik.md',
      '  S.19 Technical debt -> docs/governance/design-debt.md',
      '  S.22 Security reconciliation -> docs/audit-infrastruktur-fabrix.md + INF-01 (selesai)',
      '',
      'SEBAGIAN:',
      '  S.7 Feature inventory + S.18 fitur di luar navigasi -> AR-0 memuat halaman dan route,',
      '      TAPI belum memuat fitur yang terbangun dan tidak punya menu (S.32 dokumen UX).',
      '  S.12 State machine audit -> sapuan "terlihat bekerja padahal tidak" sudah menyentuh',
      '      tombol mati, status WO yang tak pernah tercapai, dan alert yang tak pernah dipicu.',
      '      Yang BELUM: pemetaan menyeluruh seluruh mesin status.',
      '  S.11 Source-of-truth audit -> temuan standard_cost vs harga acuan, 88 warna, dan',
      '      "dua jalur hidup" sudah menyentuh kelasnya. Yang BELUM: sapuan menyeluruh.',
      '  S.24 Test reconciliation -> docs/FABRIX_TESTING_QUALITY_ENGINEERING_GOVERNANCE.md dan',
      '      instruksi-qa0 sudah ada; AUD-43 (test yang menulis tanpa memeriksa) baru dicatat.',
      '',
      'BELUM SAMA SEKALI -- INI LINGKUP SESUNGGUHNYA:',
      '  S.9 Domain reconciliation, S.10 Entity audit, S.13 Workflow audit,',
      '  S.14 AS-IS vs TO-BE master matrix, S.20 Manufacturing readiness,',
      '  S.21 Data migration risk, S.23 Auditability, S.26 Diagram.',
      '',
      '=== KELUARAN: JANGAN 15 BERKAS ===',
      'Dokumen sendiri menulis "do not create duplicate documentation systems if one already',
      'exists". Pola yang sudah terbukti di proyek ini: 24 keluaran dokumen navigasi',
      'dikurangi jadi 3 artefak.',
      'USULAN: TIGA berkas baru saja --',
      '  1. docs/arsitektur/AS-IS-vs-TO-BE.md  (matriks utama, gabungan S.14 + S.9 + S.10)',
      '  2. docs/arsitektur/alur-kerja-dan-mesin-status.md (S.12 + S.13)',
      '  3. docs/arsitektur/risiko-migrasi-data.md (S.21 + S.20)',
      'Sisanya MENUMPANG yang sudah ada: gap/risk/decision register -> Daftar Tugas Pembangunan',
      'itu sendiri; route & feature inventory -> ar0-inventaris-as-is.md; technical debt ->',
      'design-debt.md; test coverage -> dokumen governance test; navigation status ->',
      'nav-matriks-status-dan-konflik.md.',
      '',
      '=== TAKSONOMI: JANGAN PAKAI P0-P3 ===',
      'Proyek ini punya taksonomi urgensi sendiri. PEMETAANNYA bila dokumen keluarannya',
      'terlanjur memakai P0-P3:',
      '  P0 BLOCKER      -> SUPER URGENT bila menghalangi pekerjaan berjalan, selain itu Mendesak',
      '  P1 CRITICAL     -> Mendesak',
      '  P2 IMPORTANT    -> Penting',
      '  P3 OPTIMIZATION -> Bisa Menunggu',
      'Dua taksonomi untuk satu hal adalah kelas cacat yang sudah berkali-kali menggigit',
      'proyek ini -- karena itu pemetaan ini WAJIB disebut, bukan diasumsikan.',
      '',
      '=== ATURAN MUTLAK dokumen (S.2), seluruhnya sejalan dengan doktrin yang sudah ada ===',
      '  a. Jangan membangun fitur baru selama rekonsiliasi',
      '  b. Jangan mengarang: yang tidak ditemukan dinyatakan TIDAK DITEMUKAN',
      '  c. KODE ADA BUKAN BERARTI FITUR SELESAI',
      '  d. Pertahankan perilaku yang ada',
      '  e. Pertahankan data produksi',
      'Butir (c) sudah BERKALI-KALI terbukti di sini, dan contohnya nyata bukan pinjaman:',
      '  - halaman Setelan Perhitungan dibangun, diuji lapisan servernya, dinyatakan selesai,',
      '    dan TIDAK PERNAH BISA DIBUKA SEKALI PUN (token Bearer tidak dikirim);',
      '  - alert low_stock terdaftar di skema dan ditampilkan dashboard selama berbulan-bulan',
      '    tanpa satu pun kode yang pernah membuatnya;',
      '  - tombol Tunda/Batal ada di layar dan tidak melakukan apa-apa;',
      '  - kelas cds--type-productive-heading-04 dipakai, lolos build, dan tidak pernah berlaku',
      '    karena Carbon memancarkan NOL kelas utilitas tipografi.',
      '',
      '=== S.29 ADR REGISTER -> DICATAT TERPISAH sebagai AR-02 ===',
      'Diperiksa 25 Agu 2026: register ADR TIDAK ADA di proyek ini. "ADR-005" hanya DIRUJUK',
      'di dalam dua dokumen kiriman Opus/Fable, bukan register yang kita miliki.'),
    concat_ws(chr(10),
      'DICATAT 25 Agu 2026 atas aturan "fokus satu task". Dokumen diterima saat task berjalan',
      'adalah foto profil + penerapan Carbon; tidak berhubungan, jadi DICATAT bukan dikerjakan.',
      '',
      'URGENSI "BISA MENUNGGU" -- diusulkan Claude Code, BUKAN diambil dari dokumen, karena',
      'dokumen tidak tahu keadaan antrean kita. Alasannya dua:',
      '  1. sebagian besar bagiannya SUDAH tercakup pekerjaan yang sudah jalan;',
      '  2. audit ini MEMOTRET keadaan, dan keadaannya sedang berubah cepat. Memotret sekarang',
      '     berarti potretnya usang dalam seminggu.',
      '',
      'PEMICU YANG DIUSULKAN: setelah penerapan Carbon ke seluruh halaman SELESAI. Sebelum itu,',
      'layar masih berubah tiap hari dan matriks AS-IS akan salah sebelum sempat dibaca.'));

  perform pastikan_kode_task_kosong('AR-02');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AR-02',
    'Register Keputusan Arsitektur (ADR) — Belum Ada Sama Sekali',
    'AR', 'Arsitektur',
    'Membuat register keputusan arsitektur yang bisa dirujuk, karena saat ini tidak ada.',
    'Menentukan apakah keputusan arsitektur bisa dijelaskan berbulan-bulan kemudian.',
    'bisa_menunggu', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DIPERIKSA 25 Agu 2026: TIDAK ADA register ADR di proyek ini. "ADR-005" (Production Order',
      'vs Work Order) hanya DIRUJUK di dalam dua dokumen kiriman Opus/Fable -- bukan sesuatu',
      'yang kita miliki dan bisa dibuka.',
      '',
      'SEBELUM MEMBUATNYA, periksa apakah ia benar-benar berkas ketiga atau menumpang yang ada:',
      'CLAUDE.md sudah memuat keputusan yang menentukan ARTI ANGKA, dan Daftar Tugas memuat',
      'keputusan per pekerjaan. Yang mungkin belum punya rumah: keputusan arsitektur yang',
      'tidak mengubah arti angka DAN tidak terikat satu task -- mis. "kenapa Bearer-only,',
      'bukan cookie", "kenapa lebar penuh, bukan grid Carbon".',
      '',
      'Bila jawabannya "sudah ada rumahnya", tutup task ini dengan alasan itu -- jangan membuat',
      'sistem dokumentasi ketiga hanya karena sebuah dokumen menyebutnya.'),
    'Ditemukan saat mencatat AR-01, 25 Agu 2026.');
end $mig$;
