-- PP lanjutan (26 Agu 2026): SEBAB DS-14 dicari lebih dulu, tidak langsung diperbaiki.
-- Pertanyaan pemilik produk: kenapa sebagian tabel tidak memakai kelas responsif
-- sementara yang lain di halaman yang SAMA sudah?
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  update build_tasks
     set detail_pekerjaan = detail_pekerjaan || chr(10) || concat_ws(chr(10),
       '',
       '=== SEBAB DICARI LEBIH DULU — HASILNYA, 26 Agu 2026 ===',
       '',
       'SENSUS SELURUH TABEL (bukan hanya empat halaman yang bercacat):',
       '  16 berkas halaman memuat tabel.',
       '  33 <Table> Carbon; 26 memakai .tabel-responsif, 7 TIDAK.',
       '  9 <table> mentah (angka ini turun dari 11 setelah sensus diperbaiki — lihat bawah).',
       '',
       'ENAM HALAMAN ber-tabel SEBAGIAN, dan inilah cakupan sebenarnya:',
       '  HrDashboardPage           2 tabel, 1 responsif',
       '  BomsPage                  2 tabel, 1 responsif',
       '  CustomerPurchaseOrders    2 tabel, 1 responsif',
       '  RoutingsPage              2 tabel, 1 responsif',
       '  ShipmentsPage             3 tabel, 2 responsif',
       '  WarehouseDashboardPage    3 tabel, 1 responsif',
       'Sisanya penuh: Purchasing 4/4, WorkOrders 3/3, PPIC 3/3, Production 3/3, dan',
       'lima halaman bertabel tunggal.',
       '',
       'CAKUPAN YANG BELUM BERBUNYI: dari 6 halaman itu, hanya /hr dan /warehouse yang',
       'sudah bercacat di pengukuran. EMPAT sisanya (Boms, PO klien, Routing, Pengiriman)',
       'belum — persis seperti dugaan pemilik produk: mereka menunggu kolomnya bertambah satu.',
       '',
       '=== JAWABAN 1a/1b/1c/1d — DENGAN BUKTI GIT, BUKAN DUGAAN ===',
       '',
       'a. KAPAN DITULIS: pada commit SEBELUM DS-09 (fc65305), keenam berkas itu punya',
       '   NOL <Table> Carbon. Seluruh 33 tabel Carbon lahir DI DALAM DS-09.',
       '   Dan .tabel-responsif sendiri lahir di commit yang SAMA (b2bb02b).',
       '   Jadi bukan "ditulis sebelum kelasnya ada" — tabelnya dan kelasnya lahir bersama.',
       '',
       'b. APAKAH HALAMANNYA MASUK SAPUAN: ya, keenamnya. Dan tetap terlewat.',
       '   Bukan halamannya yang tidak disentuh, melainkan TABEL KEDUANYA.',
       '',
       'c. ADAKAH CATATAN PENGECUALIAN: NOL. Tidak satu pun dari ketujuh tabel itu punya',
       '   komentar yang menyebutnya sengaja dikecualikan. Bandingkan dengan papan Gantt',
       '   PPIC, yang pengecualiannya ditulis terang-terangan di berkasnya.',
       '',
       'd. APAKAH BENTUKNYA TIDAK COCOK JADI KARTU: tidak, ketujuhnya daftar baris biasa —',
       '   absensi hari ini, komponen BOM, item PO klien, tahap routing, item pengiriman,',
       '   peringatan stok, dan PO menunggu. Semuanya cocok jadi kartu.',
       '',
       '=== KESIMPULAN: KEMUNGKINAN A (TERLEWAT), untuk KETUJUHNYA ===',
       'Dugaan arsitek benar, dan mekanismenya ternyata lebih tajam daripada "tabel kedua di',
       'bagian bawah halaman":',
       '',
       '  EMPAT dari tujuh tabel itu berada DI DALAM BARIS YANG DIMEKARKAN (Boms, PO klien,',
       '  Routing, Pengiriman). Tabel itu TIDAK ADA DI LAYAR sampai seseorang mengklik baris',
       '  untuk membukanya. Sapuan yang melihat halaman tidak akan pernah melihatnya —',
       '  begitu juga tangkapan layar, dan begitu juga pengukuran dua tepi yang baru dibuat.',
       '',
       '  TIGA sisanya tabel kedua/ketiga yang berada jauh di bawah pada halaman dashboard',
       '  (HR absensi, Gudang peringatan, Gudang PO menunggu).',
       '',
       '=== SEBAB KEDUA ADA, DAN TERBUKTI — jangan diperbaiki dengan asumsi satu sebab ===',
       'Pertanyaan pemilik produk butir 2 dijawab: YA, ada tabel yang SUDAH memakai kelas',
       'responsif tapi TETAP bercacat.',
       '  /items    : 1 tabel, 1 responsif — tetap terpotong di 672px dan 768px.',
       '  /documents: 1 tabel, 1 responsif — tetap terpotong di 672px dan 768px.',
       'Sebabnya berbeda: kelas responsif hanya berlaku DI BAWAH 672px (max-width 41,98rem).',
       'Di 672-768px tabelnya tetap berbentuk tabel, dan kolom terakhir jatuh ke luar layar.',
       'Membalik jadi kartu TIDAK menolong di rentang itu karena memang belum aktif.',
       '',
       'JADI DS-14 PUNYA TIGA SEBAB TERPISAH:',
       '  1. TOOLBAR memotong dari KIRI (360px) — /items, /documents.',
       '  2. TABEL TANPA KELAS responsif tetap jadi tabel di layar sempit — /hr, /warehouse,',
       '     ditambah 4 halaman yang belum berbunyi.',
       '  3. TABEL DENGAN KELAS tetap terpotong di 672-768px, karena kelasnya belum aktif',
       '     di rentang itu — /items, /documents, dan setiap tabel berkolom banyak lainnya.',
       'Sebab 3 adalah yang paling luas: ia tidak peduli kelasnya sudah dipasang atau belum.',
       '',
       '=== BATAS PENGUKURAN, WAJIB DISEBUT ===',
       'Angka "11 kombinasi bercacat" adalah BATAS BAWAH, bukan angka akhir. Pengukuran itu',
       'TIDAK PERNAH MEMEKARKAN SATU BARIS PUN, jadi empat tabel di dalam baris yang',
       'dimekarkan — yang justru termasuk tujuh tabel tanpa kelas — belum terukur sama sekali.',
       'Tenant uji juga kosong, sehingga barisnya memang tidak ada untuk dimekarkan.',
       '',
       '=== ATURAN BATAS PERBAIKAN (butir 3 pemilik produk) ===',
       'Kolom yang tidak penting BOLEH disembunyikan di layar sempit, TAPI HARUS TETAP BISA',
       'DIBUKA. Yang DILARANG: kolom hilang tanpa jalan melihatnya — itu persis cacat',
       'overflow-hidden yang sudah diberantas di RSP-01, dalam bentuk lain.',
       'KOLOM "AKSI" TIDAK PERNAH BOLEH DISEMBUNYIKAN: tombol yang tidak bisa dijangkau lebih',
       'buruk daripada kolom yang tidak terlihat.',
       '',
       '=== SENSUSNYA SENDIRI SEMPAT SALAH, dan diperbaiki di giliran yang sama ===',
       'Versi pertama menghitung 11 tabel mentah; dua di antaranya adalah kata <table> yang',
       'disebut di dalam KALIMAT PENJELASAN. Kelas cacat yang sama persis dengan lima penjaga',
       'yang sudah salah tuduh. Sesudah komentar dibuang lebih dulu: 9, bukan 11.'
     )
   where company_id = v_company_id and task_code = 'DS-14';

  update build_tasks
     set detail_pekerjaan = detail_pekerjaan || chr(10) || concat_ws(chr(10),
       '',
       '=== LINGKUP DIPERLUAS 26 Agu 2026 — bukan hanya elemen mentah ===',
       'Pengawas ini WAJIB juga menolak <Table> Carbon yang TIDAK memakai .tabel-responsif',
       'di berkas halaman. Alasannya diukur, bukan diduga: 7 dari 33 tabel tidak memakainya,',
       'dan NOL di antaranya punya catatan pengecualian.',
       '',
       'Dengan itu, tabel ke-34 yang lahir bulan depan tertangkap TANPA menunggu ada yang',
       'kebetulan membukanya di layar sempit. Tanpa itu, satu-satunya cara menemukannya',
       'adalah seseorang memakai HP dan menyadari ada kolom yang hilang.',
       '',
       'YANG PALING PENTING, dan ini alasan pengawas mengalahkan sapuan: EMPAT dari tujuh',
       'tabel itu ada DI DALAM BARIS YANG DIMEKARKAN — tidak terlihat di layar sampai',
       'seseorang mengklik. Sapuan visual jenis apa pun akan melewatkannya; pembacaan berkas',
       'tidak.',
       '',
       'Pakai pola penanda komentar DS-11 untuk pengecualiannya (papan Gantt PPIC dan tabel',
       'cetak surat jalan), BUKAN nomor baris, dan buang komentar sebelum menyisir — sensus',
       'yang menghasilkan angka di atas sendiri sempat menghitung kata <table> di dalam',
       'kalimat penjelasan.'
     )
   where company_id = v_company_id and task_code = 'DS-16';
end $mig$;
