-- DS-21 dan DS-22 SELESAI (27 Agu 2026).
--
-- HANYA menyentuh dua baris itu. Nol perubahan pada task lain — tidak ada urgensi yang
-- diubah, tidak ada task lain yang ditutup.
--
-- Tanpa pencarian company: penyaringnya task_code, dan build_tasks berkendala unik
-- (company_id, task_code) pada satu tenant. Pola yang sama dipakai 20260830100000.
--
-- Teks panjang lewat concat_ws(chr(10), ...) sesuai aturan proyek.

update build_tasks
set status = 'selesai',
    completed_at = now(),
    notes = concat_ws(chr(10),
      'SELESAI 27 Agu 2026. Commit: ecdf10b.',
      '',
      'AKAR PENYEBAB — satu deklarasi milik Carbon, dibaca dari paket terpasang:',
      '  .cds--progress--space-equal .cds--progress-step { min-inline-size: 8rem }',
      'Lantai 128px per langkah menahan flex-grow, sehingga langkahnya tidak bisa menyusut.',
      'Aritmetika 16 + N x 128 - 358 mereproduksi ketiga angka terukur: 0 / 42 / 170px.',
      '',
      'PERBAIKAN — memakai varian vertical Carbon, yang mencabut lantai itu',
      '(min-inline-size: initial), pada ambang yang DIHITUNG dari jumlah langkahnya:',
      '  N x 128 + 18  ->  274px (2 langkah) · 402px (3) · 530px (4)',
      '',
      'KENAPA DIHITUNG DAN BUKAN SATU AMBANG TETAP, dicatat karena ini yang berubah',
      'setelah diukur: versi pertama memakai satu ambang tetap 42rem untuk semua formulir.',
      'Ia memperbaiki ketiga formulir yang meluber TETAPI mengenakan ongkos pada formulir',
      'yang tidak pernah meluber — BOM hanya punya dua langkah, penandanya muat nyaman di',
      '360px, namun tetap dipaksa menurun dan tumbuh 28px -> 116px. Delapan puluh delapan',
      'piksel terbuang di layar terkecil untuk cacat yang tidak ia punya. Aturan proyek',
      'menjawabnya: jangan menetapkan sesuatu yang seharusnya DIHITUNG.',
      '',
      'YANG DIBANGUN:',
      '- src/lib/useMediaQuery.ts — SATU-SATUNYA kait media query, memakai',
      '  useSyncExternalStore (bukan useState + useEffect, yang menambah satu masalah lint).',
      '- src/components/ui/modal-bertahap.tsx — PenandaLangkah menghitung ambangnya sendiri.',
      '',
      'PENJAGA: tests/ds21_penanda_langkah_responsif.test.ts, 6 uji, dibuktikan MERAH lebih',
      'dulu lalu HIJAU. Yang terpenting uji (a2): ia mengikat konstanta 128px di kode ke',
      'nilai yang benar-benar dipancarkan paket Carbon. Bila Carbon mengubahnya, ambangnya',
      'ikut meleset dan luberannya kembali — tanpa satu pun test lain yang berbunyi.',
      '',
      'BUKTI TERUKUR DI PERAMBAN, 4 formulir x 6 lebar = 24 pengukuran:',
      '  PO Klien   @360: luber 170px -> 0px (menurun)',
      '  Master Item@360: luber  42px -> 0px (menurun)',
      '  Karyawan   @360: luber  42px -> 0px (menurun)',
      '  BOM        @360: luber   0px -> 0px (TETAP mendatar, tanpa ongkos)',
      '  672 / 768 / 1280 / 1440 / 1920: keempatnya mendatar, nol luber.',
      'Nol galat konsol. Seluruh langkah tampak di setiap lebar.',
      '',
      'AKSESIBILITAS: perangkap fokus 0/40 lolos maju dan 0/15 mundur, fokus terlihat 40/40,',
      'ESC menutup, seluruh langkah bernama dan dapat difokus — identik vertikal vs mendatar.',
      '',
      'ONGKOS YANG DILAPORKAN APA ADANYA: pada tiga formulir yang memang meluber, penanda',
      'tumbuh 88-204px secara vertikal di 360px. Gulir menyamping — yang dilarang keras',
      'aturan proyek — ditukar dengan gulir menurun, yang normal dan sudah ditandai Carbon',
      'lewat gradien pudar di bagian bawah isi modal.',
      '',
      'RUJUKAN KATALOG CARBON untuk perbandingan berdampingan:',
      '  https://carbondesignsystem.com/components/progress-indicator/usage/',
      '  https://carbondesignsystem.com/components/modal/usage/'
    )
where task_code = 'DS-21';

update build_tasks
set status = 'selesai',
    completed_at = now(),
    notes = concat_ws(chr(10),
      'SELESAI 27 Agu 2026. Commit: ecdf10b.',
      '',
      'AKAR PENYEBAB SEBENARNYA — dan BUKAN yang terlihat pertama kali. Analisis pertama',
      'menyimpulkan masalahnya "form mekar di layar kecil" dan menyatakan desktop',
      '"kemungkinan besar tidak bermasalah". Pemeriksaan tandingan membuktikan itu keliru,',
      'dan yang terlewat justru bagian terburuknya.',
      '',
      'Jumlah kolom ditentukan lebar LAYAR (md 672px -> 2 kolom, lg 1056px -> 4 kolom),',
      'padahal baris ini hidup DI DALAM modal, dan modal Carbon justru MENYEMPIT saat layar',
      'melebar: 84% -> 60% mulai 1056px -> 48% mulai 1312px.',
      '',
      'Dua perubahan berlawanan arah bertemu di SATU piksel viewport, terukur:',
      '  1055px -> wadah 886px -> 2 kolom -> 402px per kontrol -> helper 2 baris',
      '  1056px -> wadah 634px -> 4 kolom -> 130px per kontrol -> helper 5 baris',
      '  1312px -> wadah 630px -> 4 kolom -> 129px per kontrol -> helper 5 baris',
      'Kolom TERSEMPIT di seluruh rentang justru ada di DESKTOP, bukan di ponsel.',
      '',
      'PERBAIKAN: kedua breakpoint dicabut, diganti',
      '  grid-template-columns: repeat(auto-fit, minmax(min(15rem, 100%), 1fr))',
      'yang membaca lebar wadahnya sendiri, jadi tidak bisa lagi bertentangan dengan lebar',
      'modal. Pembungkus min(..., 100%) dipakai karena minmax(15rem, 1fr) MELUBER begitu',
      'wadahnya lebih sempit dari 15rem — persis kelas cacat yang diperbaiki DS-21.',
      '',
      'TIGA JALAN YANG DITOLAK:',
      '1. Accordion / melipat baris — Carbon melarangnya langsung di halaman pola formulir:',
      '   "Do not hide information in accordions or tabs."',
      '2. Keadaan buka-tutup per baris — barisnya di-key dengan INDEX dan removeLine',
      '   menyaring berdasarkan index, jadi keadaan lipatan akan mengikuti POSISI.',
      '3. Container query dengan ambang yang sama — lebar dalam baris di 1056px dan 1312px',
      '   keduanya di bawah 672px, jadi desktop jatuh ke satu kolom: 254px -> 446px per',
      '   baris, 76% lebih buruk.',
      '',
      'YANG SUDAH DILAKUKAN CARBON DAN SENGAJA TIDAK DIBANGUN ULANG: isi modal yang',
      'terpotong SUDAH ditandai — mask-image gradien pada .cds--modal-scroll-content yang',
      'dinyalakan ComposedModal sendiri saat scrollHeight > clientHeight, plus role="region"',
      'dan tabIndex untuk pembaca layar.',
      '',
      'PENJAGA: tests/ds22_baris_komponen_bom.test.ts, 6 uji, MERAH lebih dulu lalu HIJAU.',
      '',
      'BUKTI TERUKUR, 9 lebar x 1..4 komponen = 36 pengukuran:',
      '  lebar per kontrol  1056px: 130 -> 275px · 1312px: 129 -> 273px · 1280px: 164 -> 342px',
      '  tinggi per baris    360px: 464 -> 448px · 672px: 312 -> 296px · 768px: 296 -> 280px',
      '  0 gulir menyamping · 0 elemen melewati tepi kanan maupun kiri',
      '  0 kontrol di bawah 200px (sebelumnya 129-130px di dua lebar) · 0 galat konsol',
      '  kaki modal, tombol utama, tambah komponen, dan seluruh tombol hapus baris terlihat',
      '  dan dapat diklik di SETIAP kombinasi.',
      '',
      'YANG TIDAK BERUBAH, disebut supaya tidak dikira sudah selesai: isi modal TETAP tumbuh',
      'linier mengikuti jumlah komponen. Pertumbuhan itu melekat pada formulir berulang,',
      'ditandai Carbon lewat gradien pudar, dan tidak menyembunyikan satu pun aksi. Yang',
      'diperbaiki adalah kolom yang bertentangan dengan lebar wadahnya, bukan panjang',
      'formulirnya.',
      '',
      'TUJUH TEMPAT SEKELAS BELUM DIKERJAKAN — daftarnya ada di detail_pekerjaan task ini.',
      'RoutingsPage yang paling parah: 642px per baris di 360px, terhitung dari metrik font',
      'sungguhan.',
      '',
      'RUJUKAN KATALOG CARBON:',
      '  https://carbondesignsystem.com/patterns/forms-pattern/',
      '  https://carbondesignsystem.com/components/modal/usage/'
    )
where task_code = 'DS-22';
