-- DICATAT, BUKAN DIBANGUN (25 Agu 2026) -- aturan "fokus satu task".
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  perform pastikan_kode_task_kosong('OVR-01');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'OVR-01',
    'Tasks & Approvals — Satu Tempat untuk SELURUH Hal yang Menunggu Tindakan',
    'OVR', 'Overview',
    'Halaman lintas-workspace berisi seluruh hal yang menunggu keputusan atau tindakan seseorang.',
    'Menentukan apakah orang tahu ada pekerjaan menunggu tanpa harus membuka sembilan layar berbeda.',
    'penting', 'menunggu', 'pemilik_produk', 'Claude Code',
    concat_ws(chr(10),
      '=== E.1 SAPUAN DULU, ini yang menentukan bentuknya -- LAPORKAN sebelum membangun ===',
      'Inventaris SELURUH hal di sistem yang menunggu tindakan seseorang.',
      'Yang SUDAH DIKETAHUI (dari pemilik produk):',
      '  a. Persetujuan PO klien - tiga departemen terpisah (sudah ada)',
      '  b. Usulan standar produksi menunggu disahkan (sudah ada)',
      '  c. Antrean review absensi: di luar geofence, lupa clock-out (sudah ada)',
      '  d. Koreksi absensi dan izin menunggu keputusan (sudah ada)',
      '  e. Permintaan pembelian dari gudang (PMB-12, belum dibangun)',
      '  f. Kunci ulang baseline yang butuh alasan (sudah ada)',
      '  g. Buka kembali Work Order yang butuh alasan (sudah ada)',
      '  h. Jawaban Kamus menunggu konfirmasi (sudah ada)',
      '  i. Lot tanpa tanggal kedaluwarsa yang menunggu dilengkapi (sudah ada)',
      'CARI YANG LAIN -- sapu seluruh kode. Untuk masing-masing sebutkan: siapa yang harus',
      'bertindak, apa tindakannya, dan di mana ia muncul sekarang. CETAK DAFTARNYA.',
      '',
      '=== E.2 DARI DAFTAR ITU, USULKAN BENTUKNYA. Jangan merancang dari satu contoh ===',
      'a. Seluruhnya muat dalam satu bentuk baris yang sama, atau ada yang perlu bentuk beda?',
      'b. Bagaimana membedakan jenisnya -- pengelompokan, penanda, atau saringan?',
      'c. Tindakannya LANGSUNG di daftar atau membuka halaman aslinya? Sebagian mungkin bisa',
      '   langsung (setujui, tolak), sebagian tidak (kunci ulang baseline butuh melihat angkanya).',
      'd. Bagaimana bila satu orang punya lima puluh butir menunggu?',
      'SODORKAN, jangan putuskan sendiri.',
      '',
      '=== E.3 KENAPA SAPUAN E.1 WAJIB DULUAN ===',
      'Jenis PERTAMA yang dibangun menentukan bentuknya untuk semua yang menyusul. Bila',
      'bentuknya lahir dari permintaan pembelian saja, jenis kedua akan memaksanya berubah --',
      'kelas yang sudah berulang di proyek ini.',
      '',
      '=== E.4 YANG WAJIB ADA, apa pun bentuknya ===',
      'a. Hanya menampilkan yang menunggu tindakan ORANG YANG MEMBUKANYA.',
      'b. Urutan bawaan: paling lama menggantung di atas.',
      'c. Tiap butir menyebut: apa, dari siapa, kapan, sudah berapa lama, dan tindakannya.',
      'd. JUMLAHNYA TERLIHAT DI NAVIGASI -- angka di sebelah "Tasks & Approvals". Tanpa itu',
      '   orang harus membukanya untuk tahu ada pekerjaan menunggu.',
      'e. Riwayat bisa dilihat. Saringan: menunggu / selesai / ditolak / seluruhnya.',
      '   Bawaan: menunggu.',
      '',
      '=== E.5 JANGAN MEMINDAHKAN yang sudah ada SEKALIGUS ===',
      'a. Bangun bentuknya dengan permintaan pembelian sebagai penghuni pertama.',
      'b. Pindahkan jenis lain SATU PER SATU, masing-masing task tersendiri.',
      'c. Tempat lamanya TETAP BERFUNGSI sampai perpindahannya terbukti -- aturan "pengaman',
      '   lama dicabut hanya setelah penggantinya terbukti bekerja" berlaku.',
      'Alasan: memindahkan sembilan jenis sekaligus berarti bila ada yang rusak, tidak jelas',
      'mana penyebabnya.',
      '',
      '=== E.6-E.9 ===',
      'E.6 Halaman ini di workspace OVERVIEW sesuai sitemap IA -- pekerjaan lintas workspace.',
      'E.7 Ikuti cetakan Items untuk tabelnya; sebutkan BEDANYA saja, tidak perlu rencana',
      '    tujuh butir penuh.',
      'E.8 KOLOM untuk permintaan pembelian: bahan, jumlah dibutuhkan, diminta oleh, kapan,',
      '    untuk WO mana (tautan), status, sudah berapa lama menggantung.',
      'E.9 SIAPA MELIHAT APA: gudang/PPIC/produksi = permintaan yang MEREKA kirim beserta',
      '    statusnya; purchasing = SELURUH permintaan (itu daftar kerja mereka); pimpinan =',
      '    seluruhnya.',
      '',
      '=== E.10 PEMBERITAHUAN ===',
      'Tidak ada jalur pemberitahuan sungguhan (nol email, nol WhatsApp). Untuk sekarang cukup',
      'terlihat di layar. Begitu INF-25 (Resend) aktif, permintaan pembelian adalah kandidat',
      'PERTAMA yang layak dikirim lewat email.'),
    concat_ws(chr(10),
      'DICATAT 25 Agu 2026 atas aturan BARU "fokus satu task". Blok perintahnya lengkap dan',
      'matang; disimpan utuh supaya tidak perlu disusun ulang saat gilirannya tiba.',
      '',
      'GERBANG: E.1 (sapuan inventaris) WAJIB dilaporkan SEBELUM satu baris kode ditulis.',
      'Itu bukan formalitas -- E.3 menjelaskan kenapa: bentuk yang lahir dari satu contoh akan',
      'dipaksa berubah oleh contoh kedua.',
      '',
      'TERKAIT: PMB-12 (permintaan pembelian) adalah penghuni pertamanya. INF-25 (Resend)',
      'menentukan kapan pemberitahuan lewat email bisa menyusul.'));

  perform pastikan_kode_task_kosong('GDG-11');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'GDG-11',
    'Peringatan Bahan Bisa DITINDAKLANJUTI — Tautan WO, Tombol, dan Keadaan PO',
    'GDG', 'Gudang & Persediaan',
    'Memperluas peringatan gabungan GDG-10 supaya bisa langsung ditindaklanjuti dari tempatnya.',
    'Menentukan apakah orang harus mencari sendiri halaman berikutnya, atau bisa bertindak dari peringatannya.',
    'penting', 'menunggu', 'pemilik_produk', 'Claude Code',
    concat_ws(chr(10),
      'GDG-10 sudah menghasilkan KALIMATNYA. Yang ditambahkan di sini adalah TINDAKANNYA.',
      '',
      'a. Nomor perintah produksi di dalam peringatan jadi TAUTAN ke halaman detailnya. Bila',
      '   lebih dari satu WO membutuhkannya, sebutkan seluruhnya dengan tautan masing-masing.',
      '   Hari ini baru disebut namanya sebagai teks, dan dibatasi tiga.',
      'b. Dua bentuk menurut peran (lihat PMB-12 butir B.1 dan B.2): gudang/PPIC/produksi',
      '   melihat tombol "Kirim Permintaan"; purchasing melihat "Ajukan Pembelian".',
      'c. H.1: bila PO sudah terbit tapi barang belum datang, peringatan MENYEBUTKANNYA',
      '   ("PO sudah terbit [nomor], menunggu kedatangan"). Jangan menyuruh membeli dua kali.',
      'd. H.2: bahan yang belum punya supplier -> tombol tidak bisa ditekan, dengan keterangan',
      '   kenapa dan apa yang harus dilakukan dulu.',
      '',
      'PEMICU BERKALA masih belum ada -- lihat GDG-09/AUD-13. Peringatan yang harus ditekan',
      'orang untuk muncul bukan peringatan.'),
    concat_ws(chr(10),
      'DICATAT 25 Agu 2026 atas aturan "fokus satu task". Tergantung PMB-12 untuk tombolnya.',
      '',
      'K.2 dari blok perintah: bentuk "PERIKSA DULU" WAJIB dicatat di cetakan halaman data',
      'sebagai contoh, karena akan dirujuk untuk peringatan lain.'));
end $mig$;
