-- Blok OO (26 Agu 2026): migrasi yang ditulis tapi tidak pernah diterapkan, pengawasnya,
-- dan tiga temuan pengukuran saat memverifikasi DS-09.
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  -- ===== OO.2 — temuan: penutupan task ada di repo, tidak ada di database =====
  perform pastikan_kode_task_kosong('AUD-45');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AUD-45',
    'Migrasi Ditulis Tapi Tidak Pernah Diterapkan — Task Dilaporkan Tertutup Padahal Tidak',
    'AUD', 'Audit Kualitas',
    concat_ws(chr(10),
      'Lima berkas migrasi ditulis di repo lalu tidak pernah diterapkan ke project mana pun.',
      'Isinya penutupan DS-11 dan DS-12 serta perubahan status DS-09 jadi menunggu persetujuan.',
      'Penutupan itu ADA DI REPO dan TIDAK ADA DI DATABASE.'),
    concat_ws(chr(10),
      'Selama beberapa giliran kerja, laporan menyebut task tertutup sementara Daftar Tugas',
      'yang dibaca pemilik produk menampilkan sebaliknya. Halaman yang dipakai memantau',
      'pekerjaan menampilkan keadaan yang sudah lewat, dan tidak ada satu pun tanda bahwa',
      'ia basi.'),
    'mendesak', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'KEADAAN SAAT TEMUAN INI DICATAT (26 Agu 2026) — sudah diperbaiki, dicatat sebagai bukti:',
      '  project data nyata : 284 terpasang, 289 ada di repo -> tertinggal 5',
      '  project uji        : 284 terpasang, 289 ada di repo -> tertinggal 5',
      'Kelimanya diterapkan ke KEDUA project atas izin pemilik produk (blok OO.1), dengan',
      'potret jumlah baris SELURUH 91 tabel sebelum dan sesudah. Hasilnya: hanya build_tasks',
      'yang berubah (nyata 304 -> 308, uji 164 -> 168). Nol perubahan di 90 tabel lain.',
      '',
      'YANG MENANGKAPNYA, dan ini bagian terpentingnya: penjaga migrasi tertinggal di',
      'tests/setup/assertMigrationsUpToDate.ts — SECARA KEBETULAN. Penjaga itu dipasang untuk',
      'mencegah test berjalan di atas struktur usang, BUKAN untuk menangkap migrasi yang lupa',
      'diterapkan. Ia hanya berbunyi karena kebetulan ada yang menjalankan test.',
      '',
      'KELAS CACATNYA: "berhasil tanpa berlaku", kali ini menimpa PENCATATAN TASK itu sendiri.',
      'Berkas migrasinya ada, isinya benar, typecheck bersih, commit-nya masuk — dan tidak satu',
      'pun dari itu berarti statusnya berubah di tempat yang dibaca orang.'),
    concat_ws(chr(10),
      'SAPUAN OO.4 — apakah ini sudah terjadi sebelumnya?',
      'Disilangkan: seluruh 302 task di database dibandingkan dengan setiap kalimat di HANDOFF.md',
      'dan 25 pesan commit terakhir yang menyebut kode task bersama kata penutup.',
      'Sepuluh kandidat muncul; kesepuluhnya diperiksa satu per satu dan SELURUHNYA bukan kasus:',
      '  SEC-15  — memang dibuka kembali dengan sengaja oleh keputusan pemilik produk (KK.8).',
      '  MST-21, DS-09, INF-05, PMB-03 — berstatus menunggu persetujuan, dan itu memang maunya.',
      '  NAV-02, PLT-05, INF-18, AUD-07, MRG-13 — disebut "sebagian" atau hanya ikut tersebut',
      '  di kalimat tentang task lain.',
      'JADI: nol kasus tambahan di luar lima migrasi ini.',
      '',
      'BATAS SAPUAN INI, supaya tidak dikira lebih kuat daripada sebenarnya: ia mencocokkan',
      'kode task dan kata penutup DI BARIS YANG SAMA. Penutupan yang disebut beberapa baris',
      'jauh dari kodenya tidak akan tertangkap. Yang membuktikan kelasnya tertutup HARI INI',
      'bukan sapuan itu, melainkan bahwa kedua project kini 289 dari 289 — nol migrasi tersisa.',
      '',
      'KEJADIAN KETIGA dari kelas "task selesai tapi statusnya tertinggal", setelah MST-16,',
      'MST-17, dan DS-01. Tiga kali sudah pola — karena itu pengawasnya dicatat di AUD-46.'));

  -- ===== OO.3 — pengawas yang berbunyi tanpa menunggu ada yang menjalankan test =====
  perform pastikan_kode_task_kosong('AUD-46');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'AUD-46',
    'Pengawas Migrasi Tertinggal yang Berbunyi Tanpa Menunggu Test Dijalankan',
    'AUD', 'Audit Kualitas',
    concat_ws(chr(10),
      'Pemeriksaan berkala yang gagal keras bila ada migrasi di repo yang belum diterapkan ke',
      'project yang seharusnya — project data nyata maupun project uji.'),
    concat_ws(chr(10),
      'Penjaga yang ada sekarang menolak MENJALANKAN TEST. Yang diusulkan MEMBERI TAHU bahwa',
      'ada yang tertinggal, meski tidak ada seorang pun yang kebetulan menjalankan test.',
      'Tanpa ini, ketertinggalan hanya ketahuan saat ada yang menjalankan sesuatu — dan itulah',
      'persis mengapa AUD-45 tidak ketahuan selama beberapa giliran.'),
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'SUDAH DIPERIKSA 26 Agu 2026 — jangan ulangi penyelidikannya:',
      '',
      'BISA MENUMPANG JADWAL YANG SUDAH ADA. Bukan AUD-13 (yang itu sendiri belum dibangun,',
      'dan beberapa task lain sudah antre menumpanginya). Yang sudah benar-benar berjalan',
      'adalah .github/workflows/backup-db.yml:',
      '  - sudah ber-cron harian (0 18 * * *), jadi TIDAK perlu penjadwal ketiga;',
      '  - sudah memegang rahasia SUPABASE_ACCESS_TOKEN dan SUPABASE_PROJECT_REF, yaitu',
      '    persis kredensial yang dibutuhkan untuk membaca daftar migrasi project data nyata.',
      'Artinya ongkosnya kecil: satu skrip pembanding plus satu langkah di alur kerja itu.',
      '',
      'CARA MEMBACA MIGRASI TERPASANG, sudah terbukti bekerja: fungsi',
      'public.daftar_migrasi_terpasang() lewat kunci service_role, ATAU query langsung ke',
      'supabase_migrations.schema_migrations lewat Management API. Skema itu tidak diekspos',
      'PostgREST, jadi membacanya sebagai tabel biasa akan gagal diam-diam.',
      '',
      'SYARAT SUPAYA IA TIDAK JADI PENGAMAN YANG TIDAK BERBUNYI: gagal keras dan sebutkan',
      'ANGKANYA — berapa terpasang, berapa di repo, dan versi tertua yang belum terpasang.'),
    concat_ws(chr(10),
      'TIDAK DIBANGUN 26 Agu 2026, dan alasannya disebut supaya bisa dibantah:',
      'giliran itu sedang memverifikasi DS-09, yaitu 59 berkas sekaligus — perubahan terbesar',
      'sejauh ini. Menyisipkan langkah CI baru yang belum pernah berjalan ke dalam giliran itu',
      'menambah satu hal yang bisa gagal pada perubahan yang paling luas dampaknya.',
      '',
      'Bukan karena ongkosnya besar. Ongkosnya justru kecil, dan itu sudah diukur di atas.'));

  -- ===== Temuan OO.5b — tiga hal yang TIDAK sesuai klaim "nol halaman tersisa" =====
  perform pastikan_kode_task_kosong('DS-13');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'DS-13',
    'Sisa Cetakan Master Item: 11 Halaman Menulis Remah Roti Sendiri, dan Tabel Rincian Sales Order Masih Mentah',
    'DS', 'Design System',
    concat_ws(chr(10),
      'DS-09 melaporkan "nol halaman tersisa". Diukur ulang saat verifikasi, tiga hal tidak',
      'sesuai klaim itu — dan ketiganya bentuk yang sama: pintu bersama sudah ada, sebagian',
      'halaman tidak lewat situ.'),
    concat_ws(chr(10),
      'Perbaikan yang kelak diterapkan ke KepalaHalaman tidak akan sampai ke 11 halaman itu,',
      'persis seperti RSP-01 yang memperbaiki komponen tabel bersama dan meninggalkan 8 halaman.'),
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DIUKUR 26 Agu 2026 dengan menyisir berkas, bukan dengan menduga:',
      '',
      '1. KepalaHalaman dipakai 19 dari 39 halaman. Dari 20 sisanya, delapan memang',
      '   dikecualikan dengan alasan yang sudah tercatat (tujuh layar publik di luar kerangka',
      '   aplikasi, dan halaman cetak surat jalan). Tersisa DUA BELAS, dan sebelas di antaranya',
      '   menulis <Breadcrumb> sendiri di dalam halamannya:',
      '     AiProjectDashboardPage, AttendancePage, DebugPage, AiReadinessPage,',
      '     CompanySettingsPage, KpiPage, MyKpiPage, TestTenantPage, OperatingProfitPage,',
      '     ProcessMiningPage, WhatsNewPage.',
      '   Yang kedua belas, DashboardPage, nol remah roti — ia akar navigasi, jadi kemungkinan',
      '   besar memang benar begitu. PERIKSA DULU sebelum menyeragamkannya.',
      '   Kenapa mereka terlewat: kesebelasnya sudah dimigrasikan ke Carbon LEBIH DULU, sebelum',
      '   KepalaHalaman lahir. Jadi mereka tidak "gagal" di sapuan DS-09; mereka tidak pernah',
      '   masuk daftarnya.',
      '',
      '2. SalesOrdersPage masih memuat TIGA <table> mentah ber-Tailwind tulis tangan, di baris',
      '   631, 1130, dan 1171 — tabel rincian di dalam baris yang dimekarkan (item SO, hasil',
      '   kelayakan bahan, riwayat pengiriman). Ketiganya memakai rounded-md, yang bertentangan',
      '   dengan sudut tajam Carbon, dan warna text-muted-foreground tulis tangan.',
      '   Ini TIDAK tercatat sebagai pengecualian di mana pun. Papan Gantt PPIC tercatat;',
      '   yang ini tidak.',
      '',
      '3. TIDAK ADA PENGAWAS yang menolak <button>/<input>/<table> mentah di halaman INTERNAL.',
      '   tests/layar_publik_carbon.test.ts hanya menjaga layar publik, dan',
      '   tests/ui_raw_leak_watchdog.test.ts menjaga hal yang berbeda (kebocoran identifier).',
      '   Karena itu ketiga tabel di butir 2 lolos tanpa satu pun tanda.',
      '   Pengawas ini sudah dicatat sebagai bagian DS-2 di CLAUDE.md dan belum dibangun.'),
    concat_ws(chr(10),
      'DITEMUKAN SAAT: memverifikasi DS-09 sebelum commit (blok OO, 26 Agu 2026).',
      'DICATAT DAN TIDAK DIKERJAKAN sesuai aturan FOKUS SATU TASK.',
      '',
      'KAITANNYA DENGAN DS-09: DS-09 sedang menunggu persetujuan pemilik produk. Temuan ini',
      'TIDAK membatalkan pekerjaannya — 32 halaman memang berubah dan cetakannya memang',
      'diterapkan. Yang perlu dikoreksi adalah KLAIMNYA: "nol halaman tersisa" lebih luas',
      'daripada yang benar-benar diukur.'));

  -- ===== Temuan bukti visual — saringan tabel HILANG di layar HP =====
  perform pastikan_kode_task_kosong('DS-14');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'DS-14',
    'Saringan di Toolbar Tabel TERPOTONG KE KIRI dan Hilang Sama Sekali di Layar 360px',
    'DS', 'Design System',
    concat_ws(chr(10),
      'Di lebar 360px, kotak saringan di toolbar tabel berada SELURUHNYA di luar layar',
      'sebelah kiri. Ia tidak terpotong sebagian — ia tidak terlihat sama sekali, dan tidak',
      'ada gulir menyamping yang bisa menjangkaunya.'),
    concat_ws(chr(10),
      'Orang di lantai produksi memakai HP dan tablet. Di layar itu, menyaring tabel menjadi',
      'MUSTAHIL, dan tidak ada satu pun tanda bahwa ada kontrol yang hilang — layarnya',
      'terlihat baik-baik saja, hanya kurang satu kontrol yang tak seorang pun tahu pernah ada.'),
    'mendesak', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DIUKUR 26 Agu 2026 di peramban sungguhan, akun company.b@debug.mrp, lebar 360px,',
      'halaman /items (acuan yang sudah DISETUJUI pemilik produk):',
      '  <label class="cds--label cds--visually-hidden"> "Tipe"  -> kiri -64, kanan -63',
      '  <span class="cds--list-box__label">           "Tipe"  -> kiri -47, kanan -19',
      '  <svg> "Open menu"                                     -> kiri  -3, kanan  13',
      'Seluruhnya bernilai NEGATIF, artinya di luar tepi kiri layar.',
      '',
      'KENAPA INI TIDAK TERTANGKAP PENGUKURAN SEBELUMNYA, dan ini bagian yang layak diingat:',
      'pemeriksaan gulir menyamping membandingkan scrollWidth dengan clientWidth. Keduanya',
      '360 di sini — HALAMANNYA MEMANG TIDAK MENGGULIR. Yang meluber ke KANAN menghasilkan',
      'gulir dan berbunyi; yang terpotong ke KIRI dipotong diam-diam oleh induknya dan',
      'LOLOS DARI SETIAP PENGUKURAN YANG ADA.',
      'Sebabnya toolbar Carbon meratakan isinya ke KANAN (justify-content: flex-end) lalu',
      'memotong kelebihannya, jadi yang hilang selalu yang paling kiri.',
      '',
      'CAKUPANNYA: seluruh halaman bertabel yang memakai cetakan DS-09, bukan hanya /items.',
      'TableToolbar dipakai di 15 berkas halaman.',
      '',
      'JANGAN diperbaiki dengan flex-wrap begitu saja: toolbar Carbon bertinggi tetap 48px,',
      'dan membungkusnya akan merusak tinggi itu. Periksa dulu pola Carbon untuk toolbar di',
      'layar sempit sebelum memilih caranya.'),
    concat_ws(chr(10),
      'DITEMUKAN SAAT: mengumpulkan bukti visual DS-09 di lima lebar (blok OO.5c).',
      'DICATAT DAN TIDAK DIKERJAKAN — perbaikannya menyentuh komponen bersama yang dipakai',
      '15 halaman, jadi ia bukan "satu baris dan jelas benar", dan menyelipkannya ke dalam',
      'giliran yang sedang memverifikasi 59 berkas akan mencampur dua hal yang harus bisa',
      'dinilai terpisah.',
      '',
      'INI JUGA MENAMBAH SATU HAL KE DAFTAR PENGAWAS (lihat AUD-46 dan DS-2): pengukuran',
      'responsive yang ada hanya menghitung gulir menyamping. Pengawas yang benar juga',
      'memeriksa elemen ber-posisi NEGATIF di dalam isi halaman.'));

  -- ===== Temuan bukti visual — nama merek dan nama perusahaan bertumpuk =====
  perform pastikan_kode_task_kosong('NAV-04');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'NAV-04',
    'Nama Merek dan Nama Perusahaan Bertumpuk di Header pada Layar Sempit',
    'NAV', 'Navigasi & Shell',
    concat_ws(chr(10),
      'Di lebar 360px, tulisan "FABRIX" dan nama perusahaan saling menimpa di header atas.',
      'Nama perusahaan membungkus jadi dua baris di dalam header setinggi 48px, lalu meluap',
      'ke atas nama merek.'),
    'Header adalah satu-satunya bagian yang muncul di SETIAP halaman — cacatnya ikut ke mana-mana.',
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DIUKUR 26 Agu 2026, lebar 360px, akun company.b@debug.mrp:',
      '  .cds--header__name--prefix ("FABRIX")  -> tepi kanan 107px',
      '  .cds--header__name (isinya "Company B") -> kiri 48px, kanan 190px, TINGGI 47px',
      'Tinggi 47px pada header 48px berarti isinya sudah dua baris. Kotak nama dimulai di 48',
      'sementara prefix baru berakhir di 107 — itulah tumpang tindihnya.',
      '',
      'BUKAN DISEBABKAN DS-09: <HeaderName prefix="FABRIX"> tidak tersentuh giliran ini —',
      'ia lahir di DS-04 (commit a928586 dan 7d0385e). Diperiksa lewat git, bukan diduga.',
      '',
      'PERIKSA DI CARBON DULU: HeaderName punya perilaku bawaan untuk layar sempit',
      '(prefix disembunyikan di bawah breakpoint tertentu). Kemungkinan besar yang salah',
      'adalah cara kita memakainya, bukan komponennya — periksa halaman Usage UI Shell',
      'sebelum menimpa gayanya sendiri.'),
    concat_ws(chr(10),
      'DITEMUKAN SAAT: mengumpulkan bukti visual DS-09 di lima lebar (blok OO.5c).',
      'DICATAT DAN TIDAK DIKERJAKAN sesuai aturan FOKUS SATU TASK — ia berasal dari DS-04,',
      'bukan dari pekerjaan yang sedang berjalan.'));
end $mig$;
