-- Blok WW (26 Agu 2026): cetakan modal DISETUJUI sementara dan disapu ke seluruh modal,
-- plus koreksi notifikasi PO yang tidak pernah terlihat.
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  update build_tasks
     set status = 'menunggu_persetujuan',
         approval_review_steps = concat_ws(chr(10),
           'Buka beberapa modal di halaman yang berbeda dan bandingkan bentuknya:',
           '  /items > Tambah item        /boms > Tambah BOM',
           '  /routing > Tambah Routing   /work-orders > Buat Work Order',
           '  /purchasing > Buat PO baru  /shipments > Buat pengiriman',
           'Yang diperiksa: apakah lebarnya SAMA, dan apakah semua field satu kolom.',
           'Lalu /items > buka detail satu item > Hapus: modalnya harus JELAS LEBIH KECIL,',
           'karena isinya cuma satu pertanyaan.'),
         approval_location = 'Modal di seluruh halaman; mulai dari /items dan /boms.',
         approval_example_case = concat_ws(chr(10),
           'Buka modal Tambah item dan modal Buat BOM berdampingan. Keduanya harus selebar',
           'sama persis. Bila ada yang terasa lebih lebar atau lebih sempit, sebutkan mana.'),
         approval_if_approved = 'Tiga modal panjang (karyawan, item, BOM) dipecah jadi langkah mengikuti cetakan PO klien.',
         approval_if_rejected = 'Sebutkan modal mana dan bagian mana yang masih berbeda.',
         detail_pekerjaan = detail_pekerjaan || chr(10) || concat_ws(chr(10),
       '',
       '=== SAPUAN KE SELURUH MODAL, 26 Agu 2026 (cetakan disetujui sementara) ===',
       '',
       'SEBARAN UKURAN, sebelum -> sesudah:',
       '  sm 4  -> 6      md 10 -> 15      lg 8 -> 1',
       '',
       'TUJUH modal turun dari lg ke md karena isinya FORMULIR, bukan komponen kompleks:',
       '  HrDashboard, Boms, Items, Purchasing (PO baru), Routings, Shipments, WorkOrders.',
       'DUA modal konfirmasi berbahaya di Items naik ketegasannya jadi sm: Carbon menyediakan',
       'xs/sm justru untuk teks pendek dan SATU keputusan.',
       'SATU modal tetap lg dan itu pengecualian beralasan: pratinjau dokumen di Master',
       'Dokumen berisi PDF/gambar berukuran penuh — di situ "komponen kompleks" memang tepat.',
       '',
       'DUA KOLOM DICABUT dari formulir modal: bom-form__kisi dan kirim-form__kisi.',
       'TIDAK DICABUT, dan ini penting supaya tidak "dirapikan" nanti: kisi dua kolom di modal',
       'detail PPIC. Isinya bukan formulir melainkan DAFTAR NILAI (label di kiri, nilai di',
       'kanan). Aturan "field memenuhi lebar modal" berbicara tentang FIELD, bukan tentang',
       'daftar keterangan.',
       '',
       'PENJAGA BARU: tests/elemen_mentah_halaman_internal.test.ts kini menolak modal ber-lg',
       'di luar daftar sah. Dibuktikan MERAH dengan mengembalikan satu modal ke lg, lalu hijau',
       'lagi setelah dicabut.',
       '',
       '=== KOREKSI: NOTIFIKASI PO YANG TIDAK PERNAH TERLIHAT ===',
       'Pemilik produk melaporkan: sesudah PO disimpan tidak ada pemberitahuan apa pun.',
       'Sebabnya terbaca dari kode: pesan "PO berhasil dibuat" disetel ke formMessage TEPAT',
       'SEBELUM modalnya ditutup — jadi ia tidak pernah sempat terbaca siapa pun.',
       '',
       'Diperbaiki lewat AreaNotifikasi bersama. Terukur di peramban sesudahnya:',
       '  judul  : "PO klien berhasil dibuat"',
       '  posisi : atas 64px, kanan 16px  (di bawah header 48px)',
       '  jenis  : cds--toast-notification--success',
       '',
       'DUA CACAT LAGI TERTANGKAP HANYA KARENA MEMBUAT SATU PO DARI UJUNG KE UJUNG:',
       '',
       '1. Notifikasinya sempat ditaruh SESUDAH `await loadPurchaseOrders()`, jadi ia baru',
       '   muncul setelah tabelnya selesai dimuat ulang — layar sempat menampilkan rangka',
       '   pemuatan tanpa satu pun penjelasan bahwa penyimpanannya berhasil. Dipindah ke',
       '   sebelum muat ulang.',
       '',
       '2. Auto-pilih produk baru TIDAK PERNAH BISA BEKERJA. Kodenya membaca',
       '   `body.item.item_id` dari jawaban POST /api/items — dan endpoint itu hanya menjawab',
       '   { success: true }. Typecheck lolos, kodenya terbaca meyakinkan, dan nilainya tidak',
       '   pernah ada. Yang menemukannya bukan membaca ulang melainkan mencoba menyimpan PO',
       '   dan melihat "Item tidak valid". Diperbaiki dengan mencocokkan KODE ITEM dari daftar',
       '   yang diambil ulang.',
       '',
       'KEGAGALAN TETAP DI DALAM MODAL, keberhasilan lewat notifikasi. Bedanya bukan selera:',
       'saat gagal modalnya masih terbuka dan pesannya menyangkut field yang harus diperbaiki,',
       'jadi ia harus berada di tempat field itu.',
       '',
       'PEMBERSIHAN data uji dilaporkan: nol baris berpola UJI-NOTIF% dan nol "Klien Uji',
       'NOTIF". Yang tersisa di tenant uji adalah NOL; baris yang masih ada seluruhnya milik',
       'company_id 1 (PT ITM) dan dibuat pemilik produk sendiri hari ini — ZALA-GC60,',
       'CV Sastro Media Utama, SAS-009. Diperiksa satu per satu, bukan disimpulkan dari total.'
     )
   where company_id = v_company_id and task_code = 'DS-18';
end
$mig$;
