-- AA.3 -- laporan investigasi work_orders.status (TANPA perbaikan, sesuai
-- instruksi eksplisit: laporkan dulu, berhenti, aturan baru keputusan
-- pemilik produk). Ditambahkan sebagai temuan konkret ke PRD-12.
update public.build_tasks
set urgency = 'mendesak',
    detail_pekerjaan = detail_pekerjaan || E'\n\n---\n\nAA.3 -- TEMUAN INVESTIGASI (22 Agu 2026, laporan murni, TIDAK diperbaiki):\n\n'
  'a. NILAI YANG ADA: planned, in_progress, paused, completed, cancelled (check constraint migrasi 20260812153500). Aturan transisi SUDAH terdaftar di status_transition_rules (planned->in_progress, planned->cancelled, in_progress->paused/completed/cancelled, paused->in_progress/cancelled) -- infrastrukturnya SENGAJA dibangun lengkap, bukan draft setengah jadi. Trigger enforce_status_transition juga sudah dipasang di tabel ini (migrasi 20260817100000).\n\n'
  'b. YANG BENAR-BENAR MENGUBAH: NOL. Dikonfirmasi lewat pencarian menyeluruh TypeScript (.update ke work_orders) DAN SQL/migrasi (update/set status pada work_orders) -- keduanya nol hasil. Data live saat dicek: seluruh baris work_orders yang ada berstatus "planned". Trigger & aturan transisi di atas terpasang tapi TIDAK PERNAH tereksekusi karena tidak ada satu pun kode yang memicu UPDATE kolom ini.\n\n'
  'c. LAYAR YANG MENAMPILKAN: kolom "STATUS" di WorkOrdersPage.tsx (/work-orders, baris ~496) DAN kolom "STATUS" di kartu "Work Order" ProductionDashboardPage.tsx (/production) -- keduanya memanggil endpoint yang sama (GET /api/work-orders -> listWorkOrders.ts) yang mengembalikan `status: wo.status` apa adanya.\n\n'
  'd. DIPAKAI UNTUK KEPUTUSAN -- YA, DUA TEMPAT, INI YANG PALING PENTING:\n'
  '   1. createProductionBatch.ts baris 66: `if (wo.status === ''completed'' || wo.status === ''cancelled'') { tolak "WO ini sudah selesai/batal, tidak bisa dibuatkan batch baru" }` -- pagar keamanan SUNGGUHAN dan disengaja, TAPI KARENA status tidak pernah mencapai completed/cancelled, pagar ini PERMANEN TIDAK PERNAH AKTIF. Siapa pun bisa terus membuat batch baru di bawah Work Order yang seharusnya sudah selesai/dibatalkan, tanpa ada yang mencegahnya -- bukan cuma label yang salah, ini KONTROL YANG DIAM-DIAM TIDAK BEKERJA.\n'
  '   2. VIEW work_orders_readiness (dipakai kolom "Kesiapan"): `case when wo.status <> ''planned'' then wo.status when ada alert terbuka then ''blocked'' else ''ready'' end as readiness` -- desainnya MEMANG dibuat supaya begitu status keluar dari "planned", kolom Kesiapan langsung mencerminkan status siklus hidup itu (completed/cancelled/in_progress) alih-alih menghitung ulang alert. Karena status tidak pernah keluar dari "planned", cabang ini TIDAK PERNAH aktif -- Kesiapan SELALU dihitung dari ada/tidaknya alert terbuka saja, bagian desain yang mengikuti siklus hidup WO tidak pernah benar-benar jalan sejak awal.\n\n'
  'KESIMPULAN (bukan keputusan, murni fakta untuk bahan keputusan pemilik produk): ini BUKAN "field mati yang cuma salah label" -- ini "field mati yang menyamar sebagai pagar keamanan aktif" di createProductionBatch.ts. Sama persis kelasnya dengan tombol Tunda/Batal yang pernah ditemukan tidak berfungsi: yang berbahaya bukan layar kosong, tapi layar/kode yang TERLIHAT punya proteksi padahal tidak pernah bisa menyala.'
where task_code = 'PRD-12';
