-- Dokumen arsitektur peran & persetujuan DICATAT SEBAGAI TASK (25 Agu 2026). BUKAN dikerjakan.
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  perform pastikan_kode_task_kosong('SEC-18');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'SEC-18',
    'Arsitektur Peran, Akses & Persetujuan — 12 Fase, PEROMBAKAN Bukan Penambahan',
    'SEC', 'Keamanan & Akses',
    'Mengganti model satu-kolom-peran dengan lima dimensi: Level, Role, Position, Scope, Approval Authority.',
    'Menentukan siapa boleh melihat apa dan siapa boleh menyetujui apa, di seluruh sistem sekaligus.',
    'bisa_menunggu', 'menunggu', 'pemilik_produk', 'Claude Code',
    concat_ws(chr(10),
      'SUMBER: docs/FABRIX_User_Role_Access_Approval_Architecture_Claude_Code.md (39 bagian).',
      'Catatan kepala sudah ditambahkan di berkasnya.',
      '',
      '=== RISIKO UTAMA, BUKAN DETAIL TEKNIS ===',
      'Ini menentukan apakah tasknya berukuran MINGGU atau BULAN.',
      '  SEKARANG : SATU KOLOM PERAN per pengguna (users.role), dibaca lewat klaim JWT.',
      '  DIUSULKAN : LIMA DIMENSI terpisah -- User Level (L0-L7), Role, Position, Scope,',
      '              dan Approval Authority.',
      'Artinya SELURUH penyaringan yang bergantung pada satu kolom peran ikut berubah.',
      '',
      'ANGKANYA DIUKUR 25 Agu 2026, bukan dikutip dari dokumen:',
      '  142 aturan RLS di 81 tabel (dokumen menyebut 122 di 73 -- angka terukur yang dipakai);',
      '  51 dari 142 aturan itu MENYEBUT peran, jadi 51 itulah yang ikut goyang;',
      '  4 fungsi pembantu di database ikut terlibat: jwt_app_role, jwt_company_id,',
      '  jwt_is_company_leadership, is_super_admin_user.',
      '',
      '=== HASIL ARKEOLOGI S.2 "RECONCILE FIRST" -- SUDAH DIJALANKAN, JANGAN DIULANG ===',
      'SUDAH ADA:',
      '  users (dengan satu kolom role), autentikasi Supabase, otorisasi lewat RLS + JWT,',
      '  companies, production_plants, employees.position, employees.department,',
      '  customer_po_approvals (persetujuan per departemen: department/status/approved_by/',
      '  approved_at/notes), build_task_approval_history, data_change_audit_log, migrasi & test.',
      'SEBAGIAN:',
      '  jejak audit ADA tapi TIDAK MENYEBUT SIAPA -- diukur: 543 dari 554 baris punya',
      '  changed_by_auth_uid KOSONG dan perannya "authenticator" (peran database, bukan orang);',
      '  position & department ada sebagai ATRIBUT KARYAWAN, bukan struktur organisasi;',
      '  approval matrix ada untuk PO klien saja, belum umum.',
      'BELUM ADA SAMA SEKALI:',
      '  tabel roles, permissions, positions, departments, scope/access policy, user_level,',
      '  delegation, escalation, sessions, MFA, service/API accounts, temporary access.',
      '',
      '=== DUA BELAS FASE (S.33), sebagai sub-butir -- BUKAN 12 task ===',
      '  1 Identity/User            7 Delegation/Escalation',
      '  2 Organization/Position    8 Segregation of Duties',
      '  3 Role/Permission          9 Effective/Temporary Access',
      '  4 Scope/Access Policy     10 Security/Sessions/MFA',
      '  5 Approval Authority      11 Audit/User Activity',
      '  6 Approval Matrix         12 Service/API Accounts',
      '',
      '=== TUMPANG TINDIH -- PERIKSA SEBELUM MEMBANGUN ULANG ===',
      '  S.11-S.14 Approval Matrix -> persetujuan PO klien tiga departemen SUDAH ADA; usul-',
      '            sahkan standar produksi SUDAH ADA.',
      '  S.12 Sample Request       -> sudah tercatat di peta Sales (SLS-03), Ditunda Sadar.',
      '  S.13 Procurement approval -> MENYENTUH PMB-12 (permintaan pembelian). Kaitkan.',
      '  S.17 Segregation of Duties-> temuannya SUDAH ADA: QC dirangkap Spv Produksi sehingga',
      '            pemeriksa dan pelapor orang yang sama. Tercatat di QMS-01.',
      '  S.20 Effective-dated      -> KELAS YANG SAMA dengan HR-05 (tanggal berlaku gaji) dan',
      '            setelan bertanggal berlaku. PERIKSA apakah mekanismenya bisa dipakai ulang',
      '            alih-alih membuat yang ketiga.',
      '  S.29 Audit requirements   -> TERHALANG AUD-07. Jejak yang tidak menyebut siapa membuat',
      '            seluruh S.29 mustahil. PRASYARAT, bukan sekadar terkait.',
      '  S.23 MFA                  -> belum ada sama sekali.',
      '  S.25-S.28 Administration UX-> menyentuh penerapan Carbon yang sedang berjalan. Bila',
      '            dibangun sebelum Carbon selesai, layarnya disentuh DUA KALI.',
      '',
      '=== TIGA HAL DI DALAMNYA MENDESAK DAN BERDIRI SENDIRI ===',
      'JANGAN ditunda bersama 12 fase -- ketiganya sudah punya task sendiri:',
      '  a. pemisahan pemeriksa & pelapor QC (S.17) -> QMS-01, menyentuh audit BPOM;',
      '  b. jejak audit tidak menyebut siapa (S.29) -> AUD-07, sudah mendesak;',
      '  c. akun @debug.mrp tidak bisa dikirimi email (S.24) -> SEC-17 dan INF-26.'),
    concat_ws(chr(10),
      'DICATAT 25 Agu 2026 atas aturan "fokus satu task". Dokumen arsitektur KETIGA hari ini',
      'yang dicatat dan tidak dikerjakan.',
      '',
      '=== FAKTA YANG MENGUBAH URUTAN ===',
      'PT ITM hari ini punya 8 akun, dan SELURUHNYA berdomain @debug.mrp -- diukur, bukan',
      'diperkirakan. Belum ada satu pun akun karyawan sungguhan, dan belum ada pengguna di luar',
      'tim internal.',
      '',
      'Membangun arsitektur peran 12 fase untuk 8 akun uji berarti merancang untuk keadaan yang',
      'BELUM ADA -- dan bentuk yang benar baru terlihat setelah orang sungguhan memakainya.',
      '',
      'INI KELAS YANG SAMA DENGAN REORDER POINT: field yang dirancang sebelum ada yang',
      'memakainya ternyata TIDAK DIPAKAI SAMA SEKALI. Bedanya, di sini ongkos salah rancang',
      'jauh lebih mahal: ia menyentuh 51 aturan RLS.',
      '',
      '=== PEMICU YANG DIUSULKAN, dua-duanya dengan alasan berbeda ===',
      'Mana yang lebih dulu:',
      '  (a) ADA AKUN KARYAWAN SUNGGUHAN PERTAMA -> menentukan BENTUK yang benar. Selama',
      '      penggunanya 8 akun uji, tidak ada yang bisa membantah rancangan apa pun;',
      '  (b) PENERAPAN CARBON SELESAI -> mencegah layar administrasi (S.25-S.28) dibangun DUA',
      '      KALI.',
      'Keduanya sah, dan alasannya tidak saling menggantikan -- karena itu disebut berdua.'));
end $mig$;
