-- FND-04 diperluas: alur edit profil (25 Agu 2026, permintaan pemilik produk).
do $mig$
begin
  update build_tasks set
    name = 'Profil: Kartu Identitas Satu Tombol — Foto Diklik, Nama, Jabatan, Email',
    notes = concat_ws(chr(10), coalesce(notes, ''), '',
      '=== ALUR EDIT PROFIL, permintaan pemilik produk 25 Agu 2026 ===',
      'a. Ikon Carbon UserAvatar sebagai bawaan.',
      'b. FOTONYA SENDIRI adalah tombolnya -- diklik, jendela pilih berkas terbuka.',
      'c. Setelah dipilih, foto langsung berubah jadi PRATINJAU dengan keterangan',
      '   "Foto baru - belum tersimpan". BELUM terkirim ke server.',
      'd. Tombol "Simpan perubahan" ada DI LUAR kartu, dan menutup seluruh perubahan',
      '   identitas sekaligus. Tombol "Pilih foto"/"Simpan foto" di bawah foto DICABUT.',
      'e. Nama lengkap bisa diubah; Jabatan dan Email hanya dibaca.',
      'f. Simpan -> modal konfirmasi (Batal/Simpan) -> modal "Profil berhasil diubah".',
      '',
      '=== DUA KEPUTUSAN PEMILIK PRODUK yang menentukan artinya ===',
      '1. JABATAN menampilkan PERAN AKSES dan TIDAK BISA DIUBAH SENDIRI. Alasannya bukan',
      '   kerapian: mengubah peran sendiri berarti MENAIKKAN HAK AKSES SENDIRI.',
      '   Dua kemungkinan lain ditolak: employees.position (nol dari 8 pengguna tertaut ke',
      '   baris karyawan, dan jabatan menentukan golongan biaya direct/overhead sehingga',
      '   mengubahnya menyentuh HPP), dan kolom teks bebas baru.',
      '2. EMAIL ikut pindah ke kartu identitas, hanya dibaca. Kartu "Data akun" DIHAPUS.',
      '',
      '=== KOMPONEN CARBON, beserta alasan memilihnya ===',
      'FileUploaderButton dengan labelText berisi avatar + disableLabelChanges -- bukan',
      '<input type="file"> mentah, supaya Carbon tetap mengurus input tersembunyi,',
      'aksesibilitas, dan penyaringan format. disableLabelChanges WAJIB: tanpa itu Carbon',
      'mengganti isi label jadi nama berkas dan avatarnya lenyap.',
      'TextInput readOnly untuk Jabatan & Email -- BUKAN disabled. disabled berarti "sedang',
      'tidak bisa dipakai"; readOnly berarti "memang bukan untuk diisi".',
      'Modal transaksional untuk konfirmasi; Modal passiveModal untuk pesan berhasil.',
      '',
      'DEVIASI YANG DISADARI: Carbon lebih menganjurkan NOTIFIKASI, bukan modal, untuk pesan',
      'berhasil -- modal menghentikan pekerjaan dan harus ditutup dulu. Diminta pemilik produk',
      'secara eksplisit, jadi ini keputusan tercatat, bukan improvisasi.',
      '',
      '=== CACAT YANG DITEMUKAN & DITUTUP saat mengerjakan ini ===',
      'AppShellCarbon punya peta label peran SENDIRI, dan sudah MENYIMPANG dari getRoleLabel',
      'di src/lib/glossary.ts: LIMA dari enam belas label berbeda. Header berkata',
      '"Manager Warehouse" sementara halaman Tim berkata "Manajer Gudang" untuk orang yang',
      'sama -- melanggar aturan "satu istilah di layar untuk semua departemen". Salinan kedua',
      'DICABUT; keduanya kini memakai getRoleLabel. Dikerjakan saat itu juga karena field',
      'Jabatan yang baru harus memilih salah satu dari keduanya -- pengecualian "menghalangi".',
      '',
      '=== DIUKUR DI PERAMBAN (tenant uji company.b@debug.mrp) ===',
      '  keadaan bersih -> kartu DAN header sama-sama menampilkan ikon, nol gambar;',
      '  pilih foto -> pratinjau muncul, keterangan "belum tersimpan", tombol simpan hidup,',
      '                header BELUM berubah (memang belum disimpan);',
      '  Simpan -> modal "Simpan perubahan profil?" dengan tombol Batal & Simpan;',
      '  konfirmasi -> modal "Profil berhasil diubah", foto header berubah tanpa muat ulang;',
      '  lingkaran foto 96x96 px, jauh di atas syarat sentuh 44px;',
      '  360px: nol gulir menyamping.',
      '',
      'URUTAN SIMPAN DISENGAJA: NAMA DULU, FOTO KEMUDIAN. Bila nama gagal, tidak ada berkas',
      'foto yang terlanjur lahir di penyimpanan. Kebalikannya meninggalkan foto yatim setiap',
      'kali nama ditolak -- dan foto yatim tidak berbunyi.',
      '',
      'MASIH BELUM: blok Tanda Tangan Digital di halaman yang sama tetap memakai',
      '<input type="file"> mentah. Itu bagian penerapan Carbon, bukan bagian task ini.')
  where task_code = 'FND-04';
end $mig$;
