-- Blok ZZ (26 Agu 2026): papan Gantt PPIC dibangun ulang menurut spesifikasi Carbon,
-- plus satu temuan yang DICATAT dan TIDAK dikerjakan (aturan fokus satu task).
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  -- ===== DS-19: kemajuan papan Gantt =====
  update build_tasks
     set status = 'sedang_dikerjakan',
         detail_pekerjaan = detail_pekerjaan || chr(10) || concat_ws(chr(10),
       '',
       '=== TAMPILAN MINGGUAN DIBANGUN ULANG, 26 Agu 2026 ===',
       '',
       'BENTUK BARU, keputusan pemilik produk: "HARUSNYA MULTI LINE, WO 1 / - BATCH A /',
       '- BATCH B DST". Sumbu kiri kini WORK ORDER, dimekarkan jadi baris BATCH. Work',
       'Center TIDAK hilang: ia jadi WARNA batang dan salah satu saringan.',
       '',
       'YANG SEBELUMNYA BUKAN GANTT: papan lama adalah kisi kolom-per-hari yang selnya',
       'diisi kotak. Panjang kotak tidak mewakili durasi sama sekali, jadi "berapa lama"',
       'dan "kapan mulai" tidak bisa dibaca dari gambarnya. Sekarang posisi dan lebar',
       'batang dihitung dari menit sungguhan.',
       '',
       'DIAMBIL DARI SPESIFIKASI CARBON (dibuka & gambarnya diunduh saat sesi):',
       '  Kartu kiri: chevron, nama tebal, rentang tanggal, Tag batch + "+N", foto pelaksana',
       '  Batang: warna muda + tepi pekat, foto di kiri, GARIS PROGRES di bawah batang',
       '  BELAH KETUPAT: padat = sudah terjadi, kosong = masih rencana',
       '  GARIS SIKU penghubung antar tahap berurutan',
       '  Sumbu: nama bulan, nama hari, AKHIR PEKAN DIREDUPKAN',
       '',
       'PERMINTAAN PEMILIK PRODUK YANG DIKERJAKAN, bukan dilewati:',
       '  FOTO PELAKSANA -> ADA. Sumbernya work_order_assignments -> employees ->',
       '    users.avatar_url. Nol kolom baru. Penugasan berstatus absent/replaced TIDAK',
       '    ditampilkan: keduanya berarti orangnya justru tidak jadi mengerjakan.',
       '    CATATAN JUJUR: hari ini NOL karyawan PT ITM tertaut ke akun pengguna, jadi di',
       '    data nyata seluruh foto akan jatuh ke IKON. Bukan cacat papan.',
       '  MILESTONE -> DIGANTI YANG SERUPA. Padanan yang dipakai: scheduled_start/',
       '    scheduled_end (kosong = rencana) vs actual_start_at/actual_completed_at',
       '    (padat = sudah terjadi). Persis pasangan padat/kosong pada gambar Carbon.',
       '  SARINGAN -> ADA. Pencarian teks (batch/item/SO), Work Center, dan Sales Order.',
       '    Saringan SO hanya muncul bila ada WO yang bertaut SO.',
       '  TAB PER SO -> TIDAK, dan ini jawaban atas pertanyaan pemilik produk. Sebabnya',
       '    work_orders.sales_order_line_id BOLEH KOSONG (produksi untuk stok), jadi tab',
       '    per SO akan MENYEMBUNYIKAN Work Order yang tidak punya SO. SO jadi saringan.',
       '',
       'DIBUKTIKAN DENGAN MENJALANKAN, bukan dengan membaca:',
       '  Enam lebar wajib (360/672/768/1280/1440/1920): gulir menyamping 0, meluber ke',
       '  kanan 0, terpotong ke kiri 0. Nol galat konsol.',
       '  Isi papan terbaca dari DOM: 2 baris WO, 8 batang saat dimekarkan, 2 penghubung,',
       '  7 belah ketupat, 4 foto (1 di antaranya gambar sungguhan, sisanya ikon).',
       '  SERET-JADWALKAN-ULANG MASIH HIDUP: batang UJI-DS-A2 diseret satu kolom ke kanan',
       '  lewat tetikus sungguhan, dan planned_date-nya berubah 2026-08-25 -> 2026-08-26.',
       '',
       'PENJAGA LAMA DIPERKUAT, BUKAN DICABUT: dulu batang bisa dijatuhkan ke baris mesin',
       'lain lalu ditolak pemeriksaan. Sekarang sasaran jatuh HANYA digambar di dalam baris',
       'batch itu sendiri, dan pemeriksaannya berubah jadi "harus batch yang sama" -- lebih',
       'ketat daripada "Work Center yang sama".',
       '',
       'BELUM SELESAI, dan sengaja disebut: tampilan HARIAN dan BULANAN masih memakai kisi',
       'tabel lama beserta penanda pengecualian pengawas elemen. Keduanya menunggu giliran',
       'berikutnya di task ini.',
       '',
       'DEVIASI YANG DISEBUT TERBUKA:',
       '  1. Batang berlebar MINIMUM 44px. Tahap 2-4 jam pada kolom seminggu hanya belasan',
       '     piksel -- benar menurut skala, mustahil ditekan jari. Durasi sebenarnya tetap',
       '     tertulis di keterangan batang.',
       '  2. Nama tahap dibaca di PANEL KIRI, bukan di atas batang. Percobaan menaruhnya di',
       '     sebelah batang ditinggalkan setelah dilihat: label saling menimpa jadi',
       '     "Filadonatak2ja3 jam". Panel kiri justru yang sesuai anatomi Carbon.',
       '  3. Menu titik-tiga per baris TIDAK dibuat: tidak ada satu pun tindakan Work Order',
       '     yang berlaku dari halaman ini, dan menu kosong sudah tiga kali jadi cacat.',
       '',
       'TOKEN VISUALISASI DATA CARBON TIDAK ADA di paket terpasang (ia hidup di',
       '@carbon/charts, bukan dependensi proyek ini -- diperiksa, bukan diingat). Warna',
       'batang diambil dari palet dasar Carbon, diurutkan mengikuti anjuran resminya:',
       'warna kontras bertetangga, warna serupa dijauhkan.'
     )
   where company_id = v_company_id and task_code = 'DS-19';

  -- ===== DS-20: pengawas diperluas, dan langsung menemukan =====
  perform pastikan_kode_task_kosong('DS-20');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'DS-20',
    'Elemen Mentah di src/features/**/components/ — Wilayah yang Tidak Pernah Disisir',
    'DS', 'Design System',
    concat_ws(chr(10),
      'Pengawas elemen mentah hanya menyisir src/features/**/pages/. Berkas komponen di',
      'dalam fitur tidak pernah diperiksa sama sekali -- bukan lolos, melainkan tidak',
      'pernah ditanyai.'),
    concat_ws(chr(10),
      'Tombol, isian, dan tabel yang ditulis mentah TIDAK ikut berubah saat komponen',
      'bersama diperbaiki. NotificationBell bahkan menulis warna heksadesimal langsung',
      '(#c6c6c6, #e0e0e0, #161616) -- persis sebab "dua sistem warna" yang sudah dikeluhkan.'),
    'penting', 'menunggu', 'temuan_claude', 'Claude Code',
    concat_ws(chr(10),
      'DITEMUKAN 26 Agu 2026 saat DS-19: papan Gantt dipindahkan ke',
      'src/features/ppic/components/, dan memindahkan kode keluar dari pages/ akan',
      'MEMBUNGKAM pengawasnya tanpa ada yang memutuskannya. Pengawasnya diperluas di',
      'giliran yang sama, dan begitu diperluas ia langsung menemukan tiga pelanggaran',
      'yang selama ini tak terlihat:',
      '  src/features/mrp/components/NotificationBell.tsx -- 2 <button> mentah',
      '  src/features/signatures/components/ConfirmAndSignModal.tsx -- 1 <input> mentah',
      'Ketiganya TERCATAT sebagai UTANG di dalam pengawasnya sendiri, jadi tidak bisa',
      'bertambah diam-diam: daftar utang hanya boleh MENYUSUT.',
      '',
      'TEMUAN KEDUA, dan ini yang lebih perlu diingat: MEKANISME UTANG ITU SENDIRI TIDAK',
      'PERNAH BEKERJA. Bidangnya bernama `tag` dan diisi "button", sementara pencocokannya',
      'memakai kalimat lengkap "<button> mentah" -- jadi jatah utang tidak pernah berlaku.',
      'Tidak ada yang menyadarinya karena daftarnya masih KOSONG. Mekanisme yang belum',
      'pernah dipakai belum pernah terbukti bekerja. Sudah diperbaiki DAN dibuktikan:',
      'jatah 2 -> hijau, jatah 1 -> tepat 1 pelanggaran dilaporkan.',
      '',
      'YANG DIKERJAKAN SAAT TASK INI TIBA GILIRANNYA: ganti ketiga elemen mentah itu',
      'dengan komponen bersama, dan buang warna heksadesimal tulis tangan di',
      'NotificationBell.tsx sekalian.',
      '',
      'CATATAN: tabel cetak surat jalan (SuratJalanPreview.tsx) BUKAN bagian task ini --',
      'ia dokumen kertas, sudah ditandai sebagai pengecualian yang sah beserta alasannya.'),
    'Dicatat, TIDAK dikerjakan -- di luar lingkup DS-19.');
end
$mig$;
