-- Pola unggah gambar: notifikasi menggantikan modal berhasil (25 Agu 2026).
do $mig$
begin
  update build_tasks set
    notes = concat_ws(chr(10), coalesce(notes, ''), '',
      '=== KOREKSI PEMILIK PRODUK: IKUTI SARAN CARBON ===',
      'Modal "Profil berhasil diubah" DICABUT, diganti notifikasi sebaris.',
      'Kata pemilik produk: "ikuti saran carbon, saya yg salah".',
      '',
      'YANG BERUBAH:',
      '  - pesan BERHASIL dan GAGAL sama-sama lewat InlineNotification, bukan modal;',
      '  - dipilih InlineNotification, BUKAN ToastNotification, karena pesannya terikat pada',
      '    tindakan yang baru saja dilakukan DI HALAMAN ITU. Toast disediakan Carbon untuk',
      '    kejadian latar belakang yang jauh dari perhatian pengguna;',
      '  - modal KONFIRMASI tetap ada, karena di situ memang ada keputusan yang diambil.',
      '',
      'BEDANYA, supaya tidak tertukar lagi: MODAL UNTUK MEMUTUSKAN, NOTIFIKASI UNTUK',
      'MEMBERI TAHU.',
      '',
      '=== TANDA TANGAN IKUT POLA YANG SAMA ===',
      'Kartu Tanda Tangan Digital tidak lagi memakai <input type="file"> mentah. Gambarnya',
      'sendiri jadi tombolnya, dipratinjau dulu, tombol simpan di luar kartu, konfirmasi',
      'modal, hasil lewat notifikasi. Tombolnya TERPISAH dari tombol identitas karena',
      'akibatnya berbeda: ia menentukan gambar yang akan tercetak di dokumen berikutnya.',
      '',
      'DINAIKKAN JADI ATURAN di CLAUDE.md bagian "Pola Unggah Gambar", berlaku untuk SELURUH',
      'unggahan berikutnya -- permintaan eksplisit pemilik produk.',
      '',
      '=== DIUKUR DI PERAMBAN (tenant uji) ===',
      '  nol <input type="file"> mentah di luar komponen Carbon di halaman ini;',
      '  simpan foto -> notifikasi HIJAU "Profil berhasil diubah", NOL modal terbuka,',
      '    foto header berubah, tombol simpan mati lagi, pratinjau bersih;',
      '  pilih tanda tangan -> "Tanda tangan baru - belum tersimpan";',
      '  simpan tanda tangan -> modal "Simpan tanda tangan baru?" yang menyebut dokumen lama',
      '    TIDAK berubah, lalu notifikasi "Tanda tangan berhasil diperbarui".',
      '',
      '=== PENJAGA SUDUT TAJAM IKUT DIPERBARUI ===',
      'Daftar pengecualian bentuk bulat MENYUSUT dari dua berkas jadi satu. Itu bukan',
      'pelonggaran melainkan sebaliknya: halaman Profil dulu menulis rounded-full sendiri di',
      'JSX; sejak lingkarannya pindah ke kelas bersama, satu-satunya tempat yang menyatakan',
      '"ini bulat" tinggal satu berkas.',
      '',
      '=== CATATAN JUJUR SOAL PENGUJIAN ===',
      'Percobaan bukti pertama melaporkan alur foto GAGAL. Penyebabnya skrip ujinya sendiri:',
      'ia memakai scrollIntoView lalu jeda tetap, sementara server dev sedang meng-compile.',
      'Setelah diganti menunggu KEADAAN dan mengklik koordinat tombol modal secara langsung,',
      'alurnya lulus. Produknya tidak pernah rusak; laporannya yang salah -- kelas yang sama',
      'dengan element.click() yang tidak memicu Carbon.')
  where task_code = 'FND-04';
end $mig$;
