-- PMB-12 — Permintaan Pembelian dari gudang. DICATAT, BUKAN DIBANGUN (25 Agu 2026).
-- Blok perintahnya sudah lengkap dan matang; disimpan utuh di sini supaya tidak perlu
-- disusun ulang saat gilirannya tiba.
do $mig$
declare v_company_id integer;
begin
  select company_id into v_company_id from companies where name = 'PT ITM' limit 1;
  if v_company_id is null then return; end if;

  perform pastikan_kode_task_kosong('PMB-12');

  insert into build_tasks (company_id, task_code, name, module_code, module_name, description,
    effect_description, urgency, status, origin, pic, detail_pekerjaan, notes)
  values (v_company_id, 'PMB-12',
    'Permintaan Pembelian dari Gudang — Jejak Antara "Diminta" dan "PO Terbit"',
    'PMB', 'Pembelian & Supplier',
    'Gudang/PPIC/produksi mengirim permintaan pembelian dari peringatan bahan; purchasing menindaklanjutinya jadi PO.',
    'Mengubah permintaan yang selama ini lewat percakapan jadi jejak yang bisa dihitung.',
    'penting', 'menunggu', 'pemilik_produk', 'Claude Code',
    concat_ws(chr(10),
      '=== ARKEOLOGI SUDAH DIKERJAKAN 25 Agu 2026, hasilnya di bawah -- JANGAN diulang ===',
      '',
      'C.1 ENTITASNYA BELUM ADA. Tidak ada tabel permintaan pembelian di skema. Yang ada:',
      '    purchase_orders (PO ke supplier), customer_purchase_orders (PO dari klien), dan',
      '    leave_requests (izin HR). Tidak satu pun mendekati. Jadi ini entitas BARU.',
      '',
      'C.2 PO BISA TERISI OTOMATIS -- gerbangnya LOLOS. createPurchaseOrder menerima',
      '    supplier_id, production_plant_id, expected_date, dan lines[{item_id, qty_ordered,',
      '    unit_price}]. Bahan dan jumlah datang dari permintaan; supplier dan harga dari',
      '    supplier_item_prices (kolomnya sudah ada: supplier_id, item_id, reference_price,',
      '    min_order_qty, lead_time_days_override). Jadi "Ajukan Pembelian" TIDAK sekadar',
      '    memindahkan pekerjaan.',
      '',
      'C.3 PERAN SUDAH ADA, TIDAK PERLU PERAN BARU: purchasing_manager dan purchasing_staff',
      '    sudah terdaftar di src/lib/roles.ts, dan canManagePurchasing() sudah dipakai',
      '    createPurchaseOrder.',
      '',
      '=== B. BENTUK PERINGATAN, dua bentuk menurut peran ===',
      'B.1 PPIC/PRODUKSI/GUDANG: "Gula - sisa 80 kg dari minimal stok 200 kg. Kurang 40 kg',
      '    untuk 1 perintah produksi yang sedang berjalan." Nomor perintah produksi jadi',
      '    TAUTAN ke halaman detailnya; bila lebih dari satu, sebutkan seluruhnya dengan',
      '    tautan masing-masing. Tombol: "Kirim Permintaan".',
      'B.2 PURCHASING: "Gula - sisa 80 kg dari minimal stok 200 kg, dan dibutuhkan produksi."',
      '    Tombol: "Ajukan Pembelian" -> membuat PO bahan baku dengan bahan dan supplier',
      '    sudah terisi bila datanya ada.',
      'B.3 Sebab bertentangan tetap "PERIKSA DULU", dan tombolnya tetap ada.',
      'B.4 YANG WAJIB TERCATAT: siapa meminta, kapan, bahan apa, berapa dibutuhkan, untuk WO mana.',
      '',
      '=== D. BATAS PENGIRIMAN, DUA LAPIS, ditegakkan di DATABASE bukan tombol ===',
      'a. TIDAK BISA MEMINTA selama masih ada permintaan TERBUKA untuk bahan itu. Tombolnya',
      '   berubah jadi keterangan: "Sudah diminta [tanggal] oleh [nama] - [status]".',
      'b. Maksimal SEKALI PER HARI per bahan, sebagai pengaman tambahan.',
      'ALASAN dua lapis: (a) menghitung KEADAAN dan menjelaskan dirinya sendiri; (b)',
      'menghitung WAKTU dan menangkap kasus tak terduga. Batas harian saja punya dua celah:',
      'permintaan yang ditolak pagi ini tidak bisa diulang meski keadaan berubah, dan stok',
      'yang turun lagi setelah barang datang justru tertahan tanpa alasan.',
      '',
      '=== F. EMPAT STATUS, masing-masing punya pemicu jelas ===',
      'a. DIMINTA  - dibuat gudang lewat tombol.',
      'b. PO TERBIT - OTOMATIS saat PO supplier dibuat dari permintaan itu; permintaan',
      '   menyimpan nomor PO-nya sebagai tautan.',
      'c. SELESAI  - OTOMATIS saat barang diterima dan lot lahir.',
      'd. DITOLAK  - purchasing, WAJIB beralasan, dan gudang harus bisa melihat alasannya.',
      'JANGAN menambahkan status "dilihat purchasing" -- tidak ada tindakan yang mengikutinya.',
      'Aturan "status baru wajib punya pemicu dan akibat" berlaku penuh; ini sudah 4x jadi cacat.',
      '',
      '=== G. TUTUP LINGKARANNYA ===',
      'G.1 PO yang dibuat dari permintaan menyimpan tautan DUA ARAH.',
      'G.2 Barang diterima -> permintaan otomatis selesai.',
      'G.3 PO DIBATALKAN -> permintaan KEMBALI TERBUKA. INI YANG PALING MUDAH TERLEWAT:',
      '    permintaan itu tidak akan pernah ditindaklanjuti siapa pun, sementara bahannya',
      '    tetap tidak dibeli tanpa ada yang menyadari.',
      '',
      '=== H. KEADAAN LAIN YANG WAJIB DITANGANI ===',
      'H.1 PO sudah terbit tapi barang belum datang -> peringatan menyebutkannya ("PO sudah',
      '    terbit [nomor], menunggu kedatangan"). Jangan menyuruh membeli dua kali.',
      'H.2 Bahan BELUM PUNYA SUPPLIER -> tombol "Ajukan Pembelian" tidak bisa ditekan, dengan',
      '    keterangan kenapa dan apa yang harus dilakukan dulu.',
      'H.3 Bahan BELUM PERNAH DIBELI tidak masuk peringatan ini (keputusan yang sudah ada).',
      '',
      '=== I. ANGKA YANG PERLU TERSIMPAN ===',
      'Berapa lama dari "diminta" sampai "PO terbit". JANGAN bangun halaman laporannya',
      'sekarang -- cukup pastikan datanya tersimpan. Kandidat KPI, pemicu: setelah ada cukup data.',
      '',
      '=== J. BUKTI NEGATIF WAJIB ===',
      'J.1 kirim 2x -> ditolak, pesannya menyebut permintaan sebelumnya',
      'J.2 kirim lewat API langsung -> ditolak di DATABASE',
      'J.3 ditolak purchasing -> gudang melihat alasannya',
      'J.4 PO dibuat dari permintaan -> status berubah otomatis, tautan dua arah',
      'J.5 PO dibatalkan -> permintaan KEMBALI TERBUKA',
      'J.6 barang diterima -> permintaan selesai otomatis',
      'J.7 peran tanpa izin -> ditolak server',
      'J.8 bukti visual di 5 lebar dengan 3 peran berbeda',
      'J.9 selesai -> hilang dari daftar menunggu, muncul di riwayat'),
    concat_ws(chr(10),
      'DICATAT 25 Agu 2026 atas aturan BARU "fokus satu task": blok perintahnya lengkap,',
      'tapi TIDAK dikerjakan sekarang karena tidak berhubungan dengan task yang sedang',
      'berjalan (penerapan Carbon Design ke seluruh halaman).',
      '',
      'ALASAN B.4 yang wajib ikut tercatat, dari pemilik produk:',
      '  "Selama ini gudang memberi tahu purchasing lewat percakapan, dan tidak ada yang tahu',
      '   kapan diminta atau kapan ditindaklanjuti. Dengan permintaan yang tercatat, jarak',
      '   antara diminta dan PO terbit menjadi angka yang bisa dilihat - bahan untuk',
      '   memperbaiki proses, bukan sekadar kerapian."',
      '',
      'KEADAAN DATA NYATA SAAT DICATAT, dan ini menentukan kapan task ini berguna:',
      'PT ITM saat ini punya NOL item, NOL BOM, NOL supplier, NOL lot, NOL Work Order.',
      'Artinya H.2 ("belum punya supplier") adalah keadaan SELURUH bahan hari ini, dan',
      'peringatan bahan (GDG-10) belum bisa menyala untuk siapa pun. Task ini baru terasa',
      'gunanya setelah master data dan pembelian pertama ada.',
      '',
      'TERKAIT: GDG-10 (peringatan gabungan, sudah selesai) menyediakan tempat tombolnya.',
      'GDG-11 memperluas isi peringatannya. AA-01 (Tasks & Approvals) jadi tempat',
      'permintaan ini muncul sebagai penghuni pertama.'));
end $mig$;
